import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.features': '產品功能',
    'nav.pricing': '定價方案',
    'nav.case-studies': '客戶案例',
    'nav.about': '關於我們',
    'nav.solutions': '解決方案',
    'nav.advertiser': '我是廣告主',
    'nav.advertiser.desc': '買廣告，精準投放目標場域',
    'nav.media-owner': '我是媒體方',
    'nav.media-owner.desc': '賣版位，閒置螢幕變現',
    'nav.get-started': '免費試用',

    // Home Hero
    'home.hero.badge': '台灣首個去經銷化場域廣告 SaaS 平台',
    'home.hero.title.1': '智映媒體',
    'home.hero.title.2': '交易管理系統',
    'home.hero.description': 'AZIO1AD 重新定義廣告版位的銷售與購買方式。讓每個螢幕都成為可變現的媒體資產，打造全透明、即時化的廣告交易體驗。',
    'home.hero.cta.start': '開始免費試用',
    'home.hero.cta.demo': '預約專人演示',
    'home.hero.feature.security': '企業級資安防護',
    'home.hero.feature.instant': '即時上架銷售',

    // Home Value Prop
    'home.valueProp.title': '打破傳統廣告經銷規則',
    'home.valueProp.description': '從經銷商主導轉向自助式廣告市場。AZIO1AD 讓媒體方直接對接廣告主，消除資訊不對稱，提升成交效率。',
    'home.valueProp.card1.title': '去經銷化模式',
    'home.valueProp.card1.desc': '媒體方可自行將廣告版位快速上架販售，無需經銷商媒合，直接掌握定價權與客戶關係。',
    'home.valueProp.card2.title': '螢幕資產變現',
    'home.valueProp.card2.desc': '將原本僅具展示功能的螢幕，轉化為可販售的媒體資產，立即創造場域專屬的廣告營收。',
    'home.valueProp.card3.title': '全透明交易',
    'home.valueProp.card3.desc': '廣告主可即時查看所有版位、價格與時段，線上完成下單與素材上傳，大幅降低溝通成本。',

    // Home Features
    'home.feature1.badge': '核心功能',
    'home.feature1.title.1': '整合式場域廣告投放與',
    'home.feature1.title.2': '互動管理系統',
    'home.feature1.description': '訂閱 AZIO1AD，即可立即啟用完整的數位廣告投放與螢幕管理能力。支援多場域、多螢幕即時內容更新，內建廣告排程與時段控管。',
    'home.feature1.list.1': '雲端化廣告螢幕管理後台',
    'home.feature1.list.2': '支援多場域、多螢幕即時同步',
    'home.feature1.list.3': '內建廣告排程與播放紀錄',
    'home.feature1.list.4': '場地方兼具自營與出租能力',

    'home.feature2.badge': '生態系整合',
    'home.feature2.title.1': '廣告 × 票務 × 人流數據',
    'home.feature2.title.2': '打造完整商業閉環',
    'home.feature2.description': '與 AZIO1 票務系統深度整合，票務系統可夾帶廣告曝光與贊助內容。串接人流與購票數據，提升廣告精準度，形成生態系的第二成長曲線。',
    'home.feature2.cta': '了解更多整合方案',

    // Home CTA
    'home.cta.title': '準備好將您的螢幕變現了嗎？',
    'home.cta.description': '立即加入 AZIO1AD，體驗台灣首個去經銷化場域廣告 SaaS 平台。無論是展覽館、商場還是活動場地，我們都能為您創造價值。',
    'home.cta.button.register': '立即註冊帳號',
    'home.cta.button.contact': '聯繫銷售團隊',

    // Advertiser Page
    'advertiser.hero.badge': '我是廣告主',
    'advertiser.hero.title': '精準投放，觸及真實受眾',
    'advertiser.hero.subtitle': '告別無效曝光。AZIO1AD 讓您直接對接全台優質場域，用數據驅動預算，最大化廣告效益。',
    'advertiser.hero.cta': '開始投放廣告',
    'advertiser.why.title': '為什麼選擇 AZIO1AD？',
    'advertiser.why.description': '我們提供全透明的廣告交易環境，讓您的每一分預算都花在刀口上。',
    'advertiser.why.card1.title': '價格透明',
    'advertiser.why.card1.desc': '所有版位價格公開透明，沒有隱藏費用。',
    'advertiser.why.card2.title': '精準受眾',
    'advertiser.why.card2.desc': '結合場域人流數據，精準鎖定目標客群。',
    'advertiser.why.card3.title': '即時報表',
    'advertiser.why.card3.desc': '隨時查看廣告投放成效，優化投放策略。',
    'advertiser.marketplace.badge.status': '投放狀態',
    'advertiser.marketplace.badge.online': '即時上線中',
    'advertiser.marketplace.title': '優質廣告場域，\n盡在指尖選擇',
    'advertiser.marketplace.description': '無論是南港展覽館的巨型螢幕，還是商場的數位看板，您都能在 AZIO1AD 找到適合的曝光機會。',
    'advertiser.marketplace.feature1.title': '精準篩選',
    'advertiser.marketplace.feature1.desc': '依據地區、場域類型、人流特徵篩選最佳版位。',
    'advertiser.marketplace.feature2.title': '彈性排程',
    'advertiser.marketplace.feature2.desc': '支援單日、多日或特定時段投放，預算運用更靈活。',
    'advertiser.marketplace.feature3.title': '一站管理',
    'advertiser.marketplace.feature3.desc': '統一後台管理所有投放活動，素材更換一鍵搞定。',
    'advertiser.interaction.title': '不只是曝光，還能深度互動',
    'advertiser.interaction.description': 'AZIO1AD 獨家整合票務系統與現場互動模組。將您的廣告植入購票流程、電子票券與現場抽獎活動中，創造真實轉換。',
    'advertiser.interaction.list1': '電子票券廣告植入',
    'advertiser.interaction.list2': '現場掃碼抽獎',
    'advertiser.interaction.list3': '購票流程加購推廣',
    'advertiser.interaction.list4': '即時互動遊戲',
    'advertiser.interaction.button': '體驗互動模組',
    'advertiser.cta.title': '準備好提升品牌曝光了嗎？',
    'advertiser.cta.description': '立即註冊 AZIO1AD 廣告主帳號，首次投放即享專屬優惠。',
    'advertiser.cta.button': '免費註冊廣告主帳號',

    // Media Owner Page
    'mediaOwner.hero.badge': '我是媒體方',
    'mediaOwner.hero.title.1': '讓閒置螢幕，',
    'mediaOwner.hero.title.2': '變成現金流',
    'mediaOwner.hero.description': '無論是展覽館、商場還是活動場地。AZIO1AD 協助您將場域螢幕轉化為可變現的媒體資產，輕鬆管理、自動獲利。',
    'mediaOwner.hero.cta': '成為媒體合作夥伴',
    'mediaOwner.stats.monthly': '預估每月收益',
    'mediaOwner.stats.growth': '成長潛力',
    'mediaOwner.stats.rental': '廣告版位出租',
    'mediaOwner.stats.promotion': '自營內容推廣',
    'mediaOwner.benefits.title': '為什麼加入 AZIO1AD 媒體生態系？',
    'mediaOwner.benefits.description': '我們提供一站式 SaaS 解決方案，解決您在設備管理與廣告招商上的所有痛點。',
    'mediaOwner.benefits.card1.title': '資產變現',
    'mediaOwner.benefits.card1.desc': '將場域內的數位看板上架至公開市場，直接對接廣告主，創造額外被動收入。',
    'mediaOwner.benefits.card2.title': '自動化管理',
    'mediaOwner.benefits.card2.desc': '雲端後台統一控管所有螢幕。廣告排程、素材審核、播放監控，全部自動化完成。',
    'mediaOwner.benefits.card3.title': '去經銷化',
    'mediaOwner.benefits.card3.desc': '拿回定價權與客戶名單。不再被經銷商抽取高額佣金，實現收益最大化。',
    'mediaOwner.dashboard.badge': '強大的後台系統',
    'mediaOwner.dashboard.title.1': '一個後台，',
    'mediaOwner.dashboard.title.2': '掌控所有螢幕與收益',
    'mediaOwner.dashboard.description': '專為場域主設計的 SaaS 管理系統。無論您擁有 1 個還是 100 個螢幕，都能輕鬆進行內容派送與營收管理。',
    'mediaOwner.dashboard.feature1': '多場域集中管理',
    'mediaOwner.dashboard.feature2': '即時內容插播',
    'mediaOwner.dashboard.feature3': '收益報表分析',
    'mediaOwner.dashboard.feature4': '自訂審核機制',
    'mediaOwner.revenue.title.1': '多元變現模式，',
    'mediaOwner.revenue.title.2': '創造第二成長曲線',
    'mediaOwner.revenue.description': '除了單純的廣告版位出租，AZIO1AD 還提供更多元的獲利機會。結合票務系統與互動模組，提升場域價值。',
    'mediaOwner.revenue.card1.title': '版位出租收益',
    'mediaOwner.revenue.card1.desc': '自訂價格與時段，開放廣告主購買，獲取穩定租金。',
    'mediaOwner.revenue.card2.title': '互動模組加購',
    'mediaOwner.revenue.card2.desc': '提供抽獎、遊戲等互動功能供廣告主加購，提高客單價。',
    'mediaOwner.revenue.card3.title': '數據報告銷售',
    'mediaOwner.revenue.card3.desc': '將場域人流與受眾分析轉化為高價值的數據報告。',
    'mediaOwner.cta.title': '您的場域，值得更多價值',
    'mediaOwner.cta.description': '加入 AZIO1AD，立即開啟您的場域數位轉型之旅。',
    'mediaOwner.cta.button.apply': '申請成為媒體夥伴',
    'mediaOwner.cta.button.download': '下載合作簡報',

    // Pricing Page
    'pricing.hero.title.1': '選擇適合您的方案，',
    'pricing.hero.title.2': '開啟場域變現之旅',
    'pricing.hero.description': '無論您是單一店面還是大型展館，AZIO1AD 都有對應的解決方案。從免費體驗到完整生態系整合，助您最大化螢幕價值。',
    'pricing.plan.trial.name': '體驗版',
    'pricing.plan.trial.desc': '適合個人測試或小型場域體驗系統功能',
    'pricing.plan.trial.cta': '免費開始',
    'pricing.plan.business.name': '商務版',
    'pricing.plan.business.desc': '適合中小型場域，立即開啟廣告變現',
    'pricing.plan.business.cta': '立即訂閱',
    'pricing.plan.business.popular': '最受歡迎',
    'pricing.plan.flagship.name': '旗艦版',
    'pricing.plan.flagship.desc': '適合大型展館與連鎖品牌，完整生態系整合',
    'pricing.plan.flagship.price': '洽詢',
    'pricing.plan.flagship.cta': '聯絡我們',
    'pricing.feature.link1': '1 組播放連結',
    'pricing.feature.link5': '5 組播放連結',
    'pricing.feature.linkUnlimited': '無限組播放連結',
    'pricing.feature.scheduleBasic': '基礎雲端排程',
    'pricing.feature.scheduleAdvanced': '進階雲端排程',
    'pricing.feature.scheduleMulti': '多層級權限管理',
    'pricing.feature.qualityStandard': '標準畫質輸出',
    'pricing.feature.qualityHD': '高清畫質輸出',
    'pricing.feature.quality4K': '4K 超高清輸出',
    'pricing.feature.watermark': '畫面帶有浮水印',
    'pricing.feature.noWatermark': '去除官方浮水印',
    'pricing.feature.adSpace': '廣告版位上架權限',
    'pricing.feature.adPriority': '廣告版位優先曝光',
    'pricing.feature.interactive': '互動模組 (抽獎/遊戲)',
    'pricing.feature.api': 'API 串接',
    'pricing.feature.apiPos': 'API 串接 (票務/POS)',
    'pricing.feature.reportBasic': '基礎數據報表',
    'pricing.faq.title': '常見問題',
    'pricing.faq.q1': '什麼是「播放連結」？',
    'pricing.faq.a1': '播放連結是 AZIO1AD 系統產生的專屬網址。您只需將此網址輸入到任何連網螢幕（如智慧電視、平板或數位看板）的瀏覽器中，即可開始播放您設定的廣告內容，無需安裝額外硬體。',
    'pricing.faq.q2': '體驗版有使用期限嗎？',
    'pricing.faq.a2': '體驗版目前沒有設定硬性的使用期限，您可以盡情測試系統的穩定性與操作介面。但請注意，體驗版輸出的畫面會帶有 AZIO1AD 的浮水印，且無法使用廣告變現功能。',
    'pricing.faq.q3': '如何開始透過廣告市集獲利？',
    'pricing.faq.a3': '訂閱「商務版」或「旗艦版」後，您可以在後台設定您的螢幕版位資訊（如位置、人流、尺寸）。審核通過後，您的版位就會上架到 AZIO1AD 廣告市集，供廣告主選購。一旦有廣告主下單，您即可獲得分潤收益。',
    'pricing.faq.q4': '我可以隨時升級或取消訂閱嗎？',
    'pricing.faq.a4': '是的，您可以隨時在後台升級您的方案，新功能將即時生效。若您決定取消訂閱，服務將持續至當期計費週期結束為止。',
    'pricing.cta.title': '還不確定哪個方案適合您？',
    'pricing.cta.description': '我們的專業顧問團隊隨時準備為您服務。告訴我們您的場域規模與需求，我們將為您量身打造最合適的導入計畫。',
    'pricing.cta.button.consult': '預約專人諮詢',
    'pricing.cta.button.learnMore': '了解更多媒體方優勢',

    // Features Page
    'features.hero.title': '讓廣告，下單就能播',
    'features.hero.description': '智映（AZIO1AD）是一套把「廣告投放」做得像電商一樣簡單的系統。從媒體上架、版位選擇、下單付款，到排程播放，全都在同一個平台完成。',
    'features.card1.title': '媒體與版位上架管理',
    'features.card1.subtitle': '把螢幕，變成可以販售的媒體商品',
    'features.card1.desc1': '場域可自行建立媒體頁面（場館 / 空間 / 螢幕）',
    'features.card1.desc2': '清楚設定版位規格、尺寸、播放時段',
    'features.card1.desc3': '支援多螢幕、多場域集中管理',
    'features.card1.desc4': '即時上架、隨時調整，不需人工報價',
    'features.card1.target': '適合：展覽館、商場、活動場域、交通節點',
    'features.card2.title': '廣告版位市集 (Marketplace)',
    'features.card2.subtitle': '像逛商品一樣選廣告版位',
    'features.card2.desc1': '廣告主可直接瀏覽所有可投放版位',
    'features.card2.desc2': '依場域、時間、價格快速篩選',
    'features.card2.desc3': '每個版位資訊透明，不用來回詢價',
    'features.card2.desc4': '不經代理、不走經銷，直接媒合',
    'features.card2.highlight': '👉 去經銷化，價格與資源全面透明',
    'features.card3.title': '即時下單與排程播放',
    'features.card3.subtitle': '下單完成，系統自動幫你播',
    'features.card3.desc1': '線上下單，無需人工確認',
    'features.card3.desc2': '系統自動完成排程與播放設定',
    'features.card3.desc3': '支援指定日期、時段、輪播規則',
    'features.card3.desc4': '廣告內容可即時更新、替換',
    'features.card3.highlight': '真正做到：下單 ≠ 等待，而是立刻生效',
    'features.card4.title': '播放監控與狀態回饋',
    'features.card4.subtitle': '每一則廣告，都看得到狀態',
    'features.card4.desc1': '即時顯示播放中 / 已完成 / 排程中',
    'features.card4.desc2': '場域與螢幕狀態一目了然',
    'features.card4.desc3': '降低溝通成本，避免人工對帳與確認',
    'features.card5.title': '數據與成效追蹤（建構中）',
    'features.card5.subtitle': '讓廣告不只是播出去，而是被看見',
    'features.card5.desc1': '播放紀錄完整留存',
    'features.card5.desc2': '可結合人流 / 票務資料（依方案）',
    'features.card5.desc3': '作為後續優化投放與定價依據',
    'features.card6.title': '權限與角色管理',
    'features.card6.subtitle': '場地方、廣告主，各自專心做自己的事',
    'features.card6.desc1': '場地方：管理媒體、版位與收益',
    'features.card6.desc2': '廣告主：選位、下單、上稿、查看成效',
    'features.card6.desc3': '權限清楚分流，流程不打架',
    'features.why.title': '為什麼選擇智映？',
    'features.why.description': '智映，是一套讓廣告可以直接下單、立刻播放的系統。',
    'features.why.reason1': '廣告投放流程 全面線上化',
    'features.why.reason2': '價格、版位、播放 完全透明',
    'features.why.reason3': '去經銷、少溝通、少人力',
    'features.why.reason4': '從「播放工具」進化成「交易平台」',
    'features.cta.title': '準備好體驗全新的廣告投放模式了嗎？',
    'features.cta.description': '無論您是場域主還是廣告主，AZIO1AD 都能為您創造新的價值。',
    'features.cta.button.trial': '開始免費試用',
    'features.cta.button.demo': '預約專人演示',

    // Case Studies Page
    'caseStudies.hero.title': '成功案例',
    'caseStudies.hero.description': '看看其他場域主與廣告主如何透過 AZIO1AD 創造價值。',
    'caseStudies.card1.title': '南港展覽館',
    'caseStudies.card1.category': '展覽館',
    'caseStudies.card1.description': '透過 AZIO1AD 數位看板管理系統，成功將閒置螢幕轉化為高收益廣告版位，並大幅降低人力管理成本。',
    'caseStudies.card2.title': '信義區百貨商圈',
    'caseStudies.card2.category': '購物中心',
    'caseStudies.card2.description': '整合多個戶外大型看板，提供品牌主一站式投放服務，即時更新促銷資訊，提升轉換率。',
    'caseStudies.card3.title': '全台連鎖影城',
    'caseStudies.card3.category': '娛樂場所',
    'caseStudies.card3.description': '利用等待時間投放精準電影預告與周邊商品廣告，創造額外營收並提升觀眾體驗。',
    'caseStudies.cta.title': '您的場域也能創造同樣的價值',
    'caseStudies.cta.description': '加入 AZIO1AD，立即開啟您的場域數位轉型之旅。',
    'caseStudies.cta.primary': '成為媒體合作夥伴',
    'caseStudies.cta.secondary': '我是廣告主',
    'caseStudies.cta.button': '聯絡我們',
    'caseStudies.nangang.subtitle': '：打造全透明的數位廣告市集',
    'caseStudies.nangang.feature1.title': '雲端管理',
    'caseStudies.nangang.feature1.desc': '統一後台管理所有投放活動',
    'caseStudies.nangang.feature2.title': '版位出租收益',
    'caseStudies.nangang.feature2.desc': '自訂價格與時段，開放廣告主購買',
    'caseStudies.nangang.feature3.title': '去經銷化',
    'caseStudies.nangang.feature3.desc': '拿回定價權與客戶名單',
    'caseStudies.nangang.button': '了解更多',

    // About Page
    'about.hero.title': '連結人與場域的智慧橋樑',
    'about.hero.company': '智林國際股份有限公司',
    'about.hero.description': 'AZIO1AD 致力於打造全方位的場域媒體生態系，透過科技賦能，讓每一個場域都能發揮最大價值。',
    'about.evolution.title': '從票務到廣告的演進',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': '智林國際起步於 <strong>AZIO1 票務系統</strong>，我們深耕於大型活動與場館的票務解決方案，累積了豐富的人流數據與場域運營經驗。',
    'about.evolution.p2': '在服務過程中，我們發現場域中存在著巨大的「注意力資產」未被有效利用。傳統的廣告看板缺乏數據支持，無法精準觸及目標受眾。',
    'about.evolution.p3': '於是，我們將票務系統的人流數據與廣告投放結合，誕生了 <strong>AZIO1AD 廣告系統</strong>。這不僅是一個廣告投放平台，更是一個整合了人流、數據與場域的智慧生態系。',
    'about.ecosystem.title': '三大事業體生態系',
    'about.ecosystem.description': 'AZIO1 以數據為核心，串聯票務、廣告與電商，打造全方位的商業閉環。',
    'about.ecosystem.azio1.subtitle': '票務系統',
    'about.ecosystem.azio1.description': '專業的票務解決方案，提供購票、驗票、入場管理一站式服務，掌握核心人流數據。',
    'about.ecosystem.azio1ad.subtitle': '廣告系統',
    'about.ecosystem.azio1ad.description': '整合式場域廣告投放與管理 SaaS，將人流轉化為廣告價值，實現精準行銷。',
    'about.ecosystem.azio1ec.subtitle': '電商系統',
    'about.ecosystem.azio1ec.description': '協助 B 端客戶完成線上商務化，提供系統工具與顧問服務，建立自有品牌銷售管道。',
    'about.values.title': '我們的核心價值',
    'about.values.innovation.title': '創新 Innovation',
    'about.values.innovation.description': '持續探索新技術，為場域媒體帶來更多可能性。',
    'about.values.integration.title': '整合 Integration',
    'about.values.integration.description': '串聯票務、廣告與電商，打造無縫的商業體驗。',
    'about.values.winwin.title': '共贏 Win-Win',
    'about.values.winwin.description': '與場域主、廣告主共享價值，建立長期合作夥伴關係。',
    'about.cta.title': '您的場域，值得更多價值',
    'about.cta.description': '加入 AZIO1AD，立即開啟您的場域數位轉型之旅。',
    'about.cta.primary': '成為媒體合作夥伴',
    'about.cta.secondary': '我是廣告主',
  },
  en: {
    // Navbar
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.case-studies': 'Case Studies',
    'nav.about': 'About Us',
    'nav.solutions': 'Solutions',
    'nav.advertiser': 'For Advertisers',
    'nav.advertiser.desc': 'Buy ads, target precise venues',
    'nav.media-owner': 'For Media Owners',
    'nav.media-owner.desc': 'Monetize screens, sell inventory',
    'nav.get-started': 'Get Started',

    // Home Hero
    'home.hero.badge': 'Taiwan\'s First De-intermediated DOOH SaaS Platform',
    'home.hero.title.1': 'AZIO1AD',
    'home.hero.title.2': 'Media Exchange System',
    'home.hero.description': 'Redefining how ad inventory is sold and bought. Turn every screen into a monetizable media asset with a fully transparent, real-time trading experience.',
    'home.hero.cta.start': 'Start Free Trial',
    'home.hero.cta.demo': 'Book a Demo',
    'home.hero.feature.security': 'Enterprise Security',
    'home.hero.feature.instant': 'Instant Listing',

    // Home Value Prop
    'home.valueProp.title': 'Breaking Traditional Ad Sales Rules',
    'home.valueProp.description': 'Shifting from broker-driven to self-service ad marketplace. AZIO1AD connects media owners directly with advertisers, eliminating information asymmetry.',
    'home.valueProp.card1.title': 'De-intermediated Model',
    'home.valueProp.card1.desc': 'Media owners can list and sell ad inventory directly, controlling pricing and client relationships without intermediaries.',
    'home.valueProp.card2.title': 'Screen Monetization',
    'home.valueProp.card2.desc': 'Transform display-only screens into monetizable media assets, instantly creating venue-specific ad revenue streams.',
    'home.valueProp.card3.title': 'Transparent Trading',
    'home.valueProp.card3.desc': 'Advertisers can view all inventory, prices, and slots in real-time, completing orders online to drastically reduce communication costs.',

    // Home Features
    'home.feature1.badge': 'Core Features',
    'home.feature1.title.1': 'Integrated Ad Delivery &',
    'home.feature1.title.2': 'Interaction Management',
    'home.feature1.description': 'Subscribe to AZIO1AD to instantly enable complete digital ad delivery and screen management capabilities. Supports multi-venue, multi-screen real-time updates.',
    'home.feature1.list.1': 'Cloud-based Screen Management',
    'home.feature1.list.2': 'Multi-venue Real-time Sync',
    'home.feature1.list.3': 'Built-in Scheduling & Logs',
    'home.feature1.list.4': 'Self-use & Rental Capabilities',

    'home.feature2.badge': 'Ecosystem Integration',
    'home.feature2.title.1': 'Ads × Ticketing × Traffic Data',
    'home.feature2.title.2': 'Complete Business Loop',
    'home.feature2.description': 'Deep integration with AZIO1 ticketing system allows ads and sponsorships on tickets. Connects traffic and purchase data to improve ad precision.',
    'home.feature2.cta': 'Learn More',

    // Home CTA
    'home.cta.title': 'Ready to Monetize Your Screens?',
    'home.cta.description': 'Join AZIO1AD today and experience Taiwan\'s first de-intermediated DOOH SaaS platform. Whether exhibition halls, malls, or event venues, we create value for you.',
    'home.cta.button.register': 'Register Now',
    'home.cta.button.contact': 'Contact Sales',

    // Advertiser Page
    'advertiser.hero.badge': 'For Advertisers',
    'advertiser.hero.title': 'Precise Targeting, Real Reach',
    'advertiser.hero.subtitle': 'Say goodbye to ineffective exposure. AZIO1AD connects you directly with premium venues across Taiwan, maximizing ad effectiveness with data-driven budgets.',
    'advertiser.hero.cta': 'Start Advertising',
    'advertiser.why.title': 'Why Choose AZIO1AD?',
    'advertiser.why.description': 'We provide a fully transparent ad trading environment, ensuring every penny of your budget is well spent.',
    'advertiser.why.card1.title': 'Transparent Pricing',
    'advertiser.why.card1.desc': 'All inventory prices are open and transparent, with no hidden fees.',
    'advertiser.why.card2.title': 'Precise Audience',
    'advertiser.why.card2.desc': 'Combine venue traffic data to precisely target your ideal customers.',
    'advertiser.why.card3.title': 'Real-time Reporting',
    'advertiser.why.card3.desc': 'View ad performance anytime to optimize your delivery strategy.',
    'advertiser.marketplace.badge.status': 'Status',
    'advertiser.marketplace.badge.online': 'Live Now',
    'advertiser.marketplace.title': 'Premium Ad Venues,\nAt Your Fingertips',
    'advertiser.marketplace.description': 'From giant screens at Nangang Exhibition Center to digital signage in malls, find the perfect exposure opportunity on AZIO1AD.',
    'advertiser.marketplace.feature1.title': 'Precise Filtering',
    'advertiser.marketplace.feature1.desc': 'Filter best spots by location, venue type, and traffic characteristics.',
    'advertiser.marketplace.feature2.title': 'Flexible Scheduling',
    'advertiser.marketplace.feature2.desc': 'Support single-day, multi-day, or specific time slots for flexible budgeting.',
    'advertiser.marketplace.feature3.title': 'One-Stop Management',
    'advertiser.marketplace.feature3.desc': 'Manage all campaigns in one backend, change creatives with one click.',
    'advertiser.interaction.title': 'Not Just Exposure, Deep Interaction',
    'advertiser.interaction.description': 'AZIO1AD exclusively integrates ticketing systems and on-site interaction modules. Embed your ads in ticket flows, e-tickets, and lucky draws for real conversion.',
    'advertiser.interaction.list1': 'E-Ticket Ad Placement',
    'advertiser.interaction.list2': 'On-site QR Lucky Draw',
    'advertiser.interaction.list3': 'Ticket Add-on Promotion',
    'advertiser.interaction.list4': 'Real-time Interactive Games',
    'advertiser.interaction.button': 'Try Interactive Modules',
    'advertiser.cta.title': 'Ready to Boost Brand Exposure?',
    'advertiser.cta.description': 'Register an AZIO1AD advertiser account now and get exclusive offers for your first campaign.',
    'advertiser.cta.button': 'Free Advertiser Registration',

    // Media Owner Page
    'mediaOwner.hero.badge': 'For Media Owners',
    'mediaOwner.hero.title.1': 'Turn Idle Screens',
    'mediaOwner.hero.title.2': 'Into Cash Flow',
    'mediaOwner.hero.description': 'Whether it\'s an exhibition hall, mall, or event venue. AZIO1AD helps you transform venue screens into monetizable media assets, easily managed and automatically profitable.',
    'mediaOwner.hero.cta': 'Become a Media Partner',
    'mediaOwner.stats.monthly': 'Est. Monthly Revenue',
    'mediaOwner.stats.growth': 'Growth Potential',
    'mediaOwner.stats.rental': 'Ad Space Rental',
    'mediaOwner.stats.promotion': 'Self-Promotion',
    'mediaOwner.benefits.title': 'Why Join AZIO1AD Media Ecosystem?',
    'mediaOwner.benefits.description': 'We provide a one-stop SaaS solution to solve all your pain points in device management and ad sales.',
    'mediaOwner.benefits.card1.title': 'Asset Monetization',
    'mediaOwner.benefits.card1.desc': 'List your digital signage on the open market, connect directly with advertisers, and create extra passive income.',
    'mediaOwner.benefits.card2.title': 'Automated Management',
    'mediaOwner.benefits.card2.desc': 'Unified cloud backend control. Ad scheduling, creative review, and playback monitoring are all automated.',
    'mediaOwner.benefits.card3.title': 'De-intermediation',
    'mediaOwner.benefits.card3.desc': 'Take back pricing power and client lists. No more high commissions to brokers, maximizing your revenue.',
    'mediaOwner.dashboard.badge': 'Powerful Backend System',
    'mediaOwner.dashboard.title.1': 'One Dashboard,',
    'mediaOwner.dashboard.title.2': 'Control All Screens & Revenue',
    'mediaOwner.dashboard.description': 'SaaS management system designed for venue owners. Whether you have 1 or 100 screens, easily manage content delivery and revenue.',
    'mediaOwner.dashboard.feature1': 'Multi-venue Management',
    'mediaOwner.dashboard.feature2': 'Real-time Content Insertion',
    'mediaOwner.dashboard.feature3': 'Revenue Reports',
    'mediaOwner.dashboard.feature4': 'Custom Review Mechanism',
    'mediaOwner.revenue.title.1': 'Diverse Monetization Models,',
    'mediaOwner.revenue.title.2': 'Create a Second Growth Curve',
    'mediaOwner.revenue.description': 'Beyond simple ad space rental, AZIO1AD offers more diverse profit opportunities. Integrate ticketing systems and interactive modules to enhance venue value.',
    'mediaOwner.revenue.card1.title': 'Space Rental Revenue',
    'mediaOwner.revenue.card1.desc': 'Set your own prices and slots, open for advertisers to buy, and get stable rent.',
    'mediaOwner.revenue.card2.title': 'Interactive Module Add-ons',
    'mediaOwner.revenue.card2.desc': 'Offer lucky draws, games, etc. for advertisers to add on, increasing average order value.',
    'mediaOwner.revenue.card3.title': 'Data Report Sales',
    'mediaOwner.revenue.card3.desc': 'Transform venue traffic and audience analysis into high-value data reports.',
    'mediaOwner.cta.title': 'Your Venue Deserves More Value',
    'mediaOwner.cta.description': 'Join AZIO1AD and start your venue\'s digital transformation journey today.',
    'mediaOwner.cta.button.apply': 'Apply as Media Partner',
    'mediaOwner.cta.button.download': 'Download Deck',

    // Pricing Page
    'pricing.hero.title.1': 'Choose the Right Plan,',
    'pricing.hero.title.2': 'Start Monetizing Your Venue',
    'pricing.hero.description': 'Whether you are a single store or a large exhibition hall, AZIO1AD has a solution for you. From free trial to full ecosystem integration, maximize your screen value.',
    'pricing.plan.trial.name': 'Trial',
    'pricing.plan.trial.desc': 'For personal testing or small venue experience',
    'pricing.plan.trial.cta': 'Start Free',
    'pricing.plan.business.name': 'Business',
    'pricing.plan.business.desc': 'For SMBs, start monetizing ads immediately',
    'pricing.plan.business.cta': 'Subscribe Now',
    'pricing.plan.business.popular': 'Most Popular',
    'pricing.plan.flagship.name': 'Flagship',
    'pricing.plan.flagship.desc': 'For large venues & chains, full ecosystem integration',
    'pricing.plan.flagship.price': 'Contact Us',
    'pricing.plan.flagship.cta': 'Contact Sales',
    'pricing.feature.link1': '1 Playback Link',
    'pricing.feature.link5': '5 Playback Links',
    'pricing.feature.linkUnlimited': 'Unlimited Playback Links',
    'pricing.feature.scheduleBasic': 'Basic Cloud Scheduling',
    'pricing.feature.scheduleAdvanced': 'Advanced Cloud Scheduling',
    'pricing.feature.scheduleMulti': 'Multi-level Permissions',
    'pricing.feature.qualityStandard': 'Standard Quality Output',
    'pricing.feature.qualityHD': 'HD Quality Output',
    'pricing.feature.quality4K': '4K Ultra HD Output',
    'pricing.feature.watermark': 'Watermarked Output',
    'pricing.feature.noWatermark': 'Remove Official Watermark',
    'pricing.feature.adSpace': 'Ad Space Listing Rights',
    'pricing.feature.adPriority': 'Priority Ad Exposure',
    'pricing.feature.interactive': 'Interactive Modules (Draw/Game)',
    'pricing.feature.api': 'API Integration',
    'pricing.feature.apiPos': 'API Integration (Ticketing/POS)',
    'pricing.feature.reportBasic': 'Basic Data Reports',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'What is a "Playback Link"?',
    'pricing.faq.a1': 'A Playback Link is a unique URL generated by AZIO1AD. Simply enter this URL into the browser of any connected screen (Smart TV, Tablet, Digital Signage) to start playing your content, no extra hardware needed.',
    'pricing.faq.q2': 'Is there a time limit for the Trial?',
    'pricing.faq.a2': 'There is currently no hard time limit for the Trial version. You can test the system stability and interface as much as you like. However, the output will have an AZIO1AD watermark and ad monetization is disabled.',
    'pricing.faq.q3': 'How do I start earning from the Ad Marketplace?',
    'pricing.faq.a3': 'After subscribing to Business or Flagship plans, you can set up your screen inventory info (location, traffic, size) in the backend. Once approved, your inventory is listed on the AZIO1AD Ad Marketplace for advertisers to buy. You earn revenue when ads are purchased.',
    'pricing.faq.q4': 'Can I upgrade or cancel anytime?',
    'pricing.faq.a4': 'Yes, you can upgrade your plan in the backend anytime, and new features take effect immediately. If you cancel, the service continues until the end of the current billing cycle.',
    'pricing.cta.title': 'Not sure which plan fits you?',
    'pricing.cta.description': 'Our professional consulting team is ready to help. Tell us your venue scale and needs, and we will tailor the best implementation plan for you.',
    'pricing.cta.button.consult': 'Book Consultation',
    'pricing.cta.button.learnMore': 'Learn More Media Benefits',

    // Features Page
    'features.hero.title': 'Ads that Play as Soon as You Order',
    'features.hero.description': 'AZIO1AD makes ad placement as simple as e-commerce. From listing media and selecting spots to ordering and scheduling, everything is done on one platform.',
    'features.card1.title': 'Media & Inventory Management',
    'features.card1.subtitle': 'Turn Screens into Sellable Media Products',
    'features.card1.desc1': 'Venues can create media pages (Venue / Space / Screen)',
    'features.card1.desc2': 'Clearly define specs, sizes, and playback times',
    'features.card1.desc3': 'Centralized management for multiple screens and venues',
    'features.card1.desc4': 'Instant listing and adjustment, no manual quoting needed',
    'features.card1.target': 'Best for: Exhibition Halls, Malls, Event Venues, Transit Hubs',
    'features.card2.title': 'Ad Marketplace',
    'features.card2.subtitle': 'Shop for Ad Spots Like Products',
    'features.card2.desc1': 'Advertisers can browse all available spots directly',
    'features.card2.desc2': 'Filter by venue, time, and price quickly',
    'features.card2.desc3': 'Transparent info for every spot, no back-and-forth inquiries',
    'features.card2.desc4': 'Direct matching, no agencies or brokers needed',
    'features.card2.highlight': '👉 De-intermediated, fully transparent pricing & resources',
    'features.card3.title': 'Instant Ordering & Scheduling',
    'features.card3.subtitle': 'Order Complete, System Plays Automatically',
    'features.card3.desc1': 'Online ordering, no manual confirmation required',
    'features.card3.desc2': 'System automatically handles scheduling and playback settings',
    'features.card3.desc3': 'Supports specific dates, times, and rotation rules',
    'features.card3.desc4': 'Ad content can be updated and replaced instantly',
    'features.card3.highlight': 'True Instant: Order ≠ Wait, it means Live immediately',
    'features.card4.title': 'Playback Monitoring & Feedback',
    'features.card4.subtitle': 'See the Status of Every Ad',
    'features.card4.desc1': 'Real-time status: Playing / Completed / Scheduled',
    'features.card4.desc2': 'Venue and screen status at a glance',
    'features.card4.desc3': 'Reduces communication costs and manual reconciliation',
    'features.card5.title': 'Data & Performance Tracking (Coming Soon)',
    'features.card5.subtitle': 'Make Ads Seen, Not Just Played',
    'features.card5.desc1': 'Complete playback logs retained',
    'features.card5.desc2': 'Integrate with foot traffic / ticketing data (per plan)',
    'features.card5.desc3': 'Basis for optimizing future placements and pricing',
    'features.card6.title': 'Permission & Role Management',
    'features.card6.subtitle': 'Venues and Advertisers Focus on Their Own Tasks',
    'features.card6.desc1': 'Venues: Manage media, inventory, and revenue',
    'features.card6.desc2': 'Advertisers: Select spots, order, upload, view results',
    'features.card6.desc3': 'Clear permission separation, no workflow conflicts',
    'features.why.title': 'Why Choose AZIO1AD?',
    'features.why.description': 'AZIO1AD is a system that lets ads be ordered directly and played immediately.',
    'features.why.reason1': 'Fully Online Ad Placement Process',
    'features.why.reason2': 'Completely Transparent Price, Inventory, Playback',
    'features.why.reason3': 'No Middlemen, Less Communication, Less Labor',
    'features.why.reason4': 'Evolving from "Playback Tool" to "Trading Platform"',
    'features.cta.title': 'Ready to Experience the New Ad Model?',
    'features.cta.description': 'Whether you are a venue owner or an advertiser, AZIO1AD creates new value for you.',
    'features.cta.button.trial': 'Start Free Trial',
    'features.cta.button.demo': 'Book a Demo',

    // Case Studies Page
    'caseStudies.hero.title': 'Case Studies',
    'caseStudies.hero.description': 'See how other venue owners and advertisers create value with AZIO1AD.',
    'caseStudies.card1.title': 'Nangang Exhibition Center',
    'caseStudies.card1.category': 'Exhibition Hall',
    'caseStudies.card1.description': 'Successfully transformed idle screens into high-yield ad spots using AZIO1AD digital signage management system, significantly reducing labor costs.',
    'caseStudies.card2.title': 'Xinyi District Shopping Area',
    'caseStudies.card2.category': 'Shopping Mall',
    'caseStudies.card2.description': 'Integrated multiple large outdoor billboards to provide brands with one-stop placement services, updating promotional info in real-time to boost conversion.',
    'caseStudies.card3.title': 'National Cinema Chain',
    'caseStudies.card3.category': 'Entertainment Venue',
    'caseStudies.card3.description': 'Utilized wait times to broadcast precise movie trailers and merchandise ads, creating extra revenue and enhancing viewer experience.',
    'caseStudies.cta.title': 'Your Venue Can Create Value Too',
    'caseStudies.cta.description': 'Join AZIO1AD and start your venue digital transformation journey today.',
    'caseStudies.cta.primary': 'Become a Media Partner',
    'caseStudies.cta.secondary': 'I am an Advertiser',
    'caseStudies.cta.button': 'Contact Us',
    'caseStudies.nangang.subtitle': ': Building a Fully Transparent Digital Ad Marketplace',
    'caseStudies.nangang.feature1.title': 'Cloud Management',
    'caseStudies.nangang.feature1.desc': 'Unified backend to manage all campaigns',
    'caseStudies.nangang.feature2.title': 'Rental Revenue',
    'caseStudies.nangang.feature2.desc': 'Set prices and slots, open for purchase',
    'caseStudies.nangang.feature3.title': 'De-intermediation',
    'caseStudies.nangang.feature3.desc': 'Take back pricing power and client lists',
    'caseStudies.nangang.button': 'Learn More',

    // About Page
    'about.hero.title': 'Connecting People and Spaces',
    'about.hero.company': 'AZIO1 International Co., Ltd.',
    'about.hero.description': 'AZIO1AD is dedicated to building a comprehensive venue media ecosystem, empowering every venue to maximize its value through technology.',
    'about.evolution.title': 'From Ticketing to Advertising',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': 'AZIO1 started with the <strong>AZIO1 Ticketing System</strong>, deeply cultivating ticketing solutions for large events and venues, accumulating rich foot traffic data and venue operation experience.',
    'about.evolution.p2': 'During our service, we discovered huge "attention assets" in venues that were not effectively utilized. Traditional billboards lack data support and cannot accurately reach target audiences.',
    'about.evolution.p3': 'Thus, we combined ticketing foot traffic data with advertising to create the <strong>AZIO1AD Advertising System</strong>. This is not just an ad platform, but a smart ecosystem integrating people, data, and venues.',
    'about.ecosystem.title': 'Three Business Ecosystems',
    'about.ecosystem.description': 'AZIO1 uses data as the core to connect ticketing, advertising, and e-commerce, creating a comprehensive business loop.',
    'about.ecosystem.azio1.subtitle': 'Ticketing System',
    'about.ecosystem.azio1.description': 'Professional ticketing solutions providing one-stop services for purchasing, validation, and entry management, mastering core foot traffic data.',
    'about.ecosystem.azio1ad.subtitle': 'Advertising System',
    'about.ecosystem.azio1ad.description': 'Integrated on-site ad delivery and management SaaS, transforming foot traffic into ad value for precision marketing.',
    'about.ecosystem.azio1ec.subtitle': 'E-commerce System',
    'about.ecosystem.azio1ec.description': 'Assisting B-side clients in online commerce, providing system tools and consulting services to build their own brand sales channels.',
    'about.values.title': 'Our Core Values',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'Continuously exploring new technologies to bring more possibilities to venue media.',
    'about.values.integration.title': 'Integration',
    'about.values.integration.description': 'Connecting ticketing, advertising, and e-commerce to create a seamless business experience.',
    'about.values.winwin.title': 'Win-Win',
    'about.values.winwin.description': 'Sharing value with venue owners and advertisers to build long-term partnerships.',
    'about.cta.title': 'Your Venue Deserves More Value',
    'about.cta.description': 'Join AZIO1AD and start your venue digital transformation journey today.',
    'about.cta.primary': 'Become a Media Partner',
    'about.cta.secondary': 'I am an Advertiser',
  },
  ja: {
    // Navbar
    'nav.features': '機能',
    'nav.pricing': '料金プラン',
    'nav.case-studies': '導入事例',
    'nav.about': '私たちについて',
    'nav.solutions': 'ソリューション',
    'nav.advertiser': '広告主の方へ',
    'nav.advertiser.desc': '広告を購入し、ターゲット層にリーチ',
    'nav.media-owner': '媒体主の方へ',
    'nav.media-owner.desc': 'スクリーンを収益化し、広告枠を販売',
    'nav.get-started': '無料で始める',

    // Home Hero
    'home.hero.badge': '台湾初の脱仲介型DOOH SaaSプラットフォーム',
    'home.hero.title.1': 'AZIO1AD',
    'home.hero.title.2': 'メディア取引管理システム',
    'home.hero.description': '広告枠の売買方法を再定義します。すべてのスクリーンを収益可能なメディア資産に変え、完全に透明でリアルタイムな広告取引体験を提供します。',
    'home.hero.cta.start': '無料で試す',
    'home.hero.cta.demo': 'デモを予約',
    'home.hero.feature.security': 'エンタープライズ級のセキュリティ',
    'home.hero.feature.instant': '即時出品・販売',

    // Home Value Prop
    'home.valueProp.title': '従来の広告販売ルールを打破',
    'home.valueProp.description': '仲介業者主導からセルフサービス型の広告市場へ。AZIO1ADは媒体主と広告主を直接つなぎ、情報の非対称性を解消し、取引効率を向上させます。',
    'home.valueProp.card1.title': '脱仲介モデル',
    'home.valueProp.card1.desc': '媒体主は広告枠を自ら迅速に出品・販売でき、仲介業者を介さずに価格決定権と顧客関係を直接管理できます。',
    'home.valueProp.card2.title': 'スクリーンの収益化',
    'home.valueProp.card2.desc': '表示機能のみだったスクリーンを販売可能なメディア資産に変え、施設独自の広告収益源を即座に創出します。',
    'home.valueProp.card3.title': '透明な取引',
    'home.valueProp.card3.desc': '広告主はすべての広告枠、価格、時間帯をリアルタイムで確認でき、オンラインで注文と素材アップロードを完了できるため、コミュニケーションコストを大幅に削減できます。',

    // Home Features
    'home.feature1.badge': 'コア機能',
    'home.feature1.title.1': '統合型広告配信＆',
    'home.feature1.title.2': 'インタラクション管理',
    'home.feature1.description': 'AZIO1ADを購読すると、完全なデジタル広告配信とスクリーン管理機能を即座に利用できます。複数施設、複数スクリーンのリアルタイム更新に対応しています。',
    'home.feature1.list.1': 'クラウド型スクリーン管理',
    'home.feature1.list.2': '複数施設・スクリーンのリアルタイム同期',
    'home.feature1.list.3': 'スケジュール管理と再生ログ機能',
    'home.feature1.list.4': '自社利用と外部販売の両立',

    'home.feature2.badge': 'エコシステム統合',
    'home.feature2.title.1': '広告 × チケット × 人流データ',
    'home.feature2.title.2': '完全なビジネスループの構築',
    'home.feature2.description': 'AZIO1チケットシステムとの深い統合により、チケットに広告やスポンサー情報を掲載可能。人流と購入データを連携させ、広告の精度を向上させます。',
    'home.feature2.cta': '詳細を見る',

    // Home CTA
    'home.cta.title': 'スクリーンの収益化を始めませんか？',
    'home.cta.description': '今すぐAZIO1ADに参加し、台湾初の脱仲介型DOOH SaaSプラットフォームを体験してください。展示場、ショッピングモール、イベント会場など、あらゆる場所で価値を創造します。',
    'home.cta.button.register': '今すぐ登録',
    'home.cta.button.contact': '営業チームに連絡',

    // Advertiser Page
    'advertiser.hero.badge': '広告主の方へ',
    'advertiser.hero.title': '精密なターゲティング、真のオーディエンスにリーチ',
    'advertiser.hero.subtitle': '無効な露出に別れを告げましょう。AZIO1ADは台湾全土のプレミアム会場と直接つながり、データ駆動型の予算で広告効果を最大化します。',
    'advertiser.hero.cta': '広告配信を開始',
    'advertiser.why.title': 'なぜAZIO1ADを選ぶのか？',
    'advertiser.why.description': '完全に透明な広告取引環境を提供し、予算を最大限に活用できるようにします。',
    'advertiser.why.card1.title': '透明な価格設定',
    'advertiser.why.card1.desc': 'すべての広告枠の価格は公開されており、隠れた費用はありません。',
    'advertiser.why.card2.title': '正確なオーディエンス',
    'advertiser.why.card2.desc': '施設の人流データを組み合わせ、ターゲット顧客を正確に狙い撃ちします。',
    'advertiser.why.card3.title': 'リアルタイムレポート',
    'advertiser.why.card3.desc': 'いつでも広告パフォーマンスを確認し、配信戦略を最適化できます。',
    'advertiser.marketplace.badge.status': 'ステータス',
    'advertiser.marketplace.badge.online': '配信中',
    'advertiser.marketplace.title': 'プレミアムな広告会場、\n指先で選択',
    'advertiser.marketplace.description': '南港展覧館の巨大スクリーンからショッピングモールのデジタルサイネージまで、AZIO1ADで最適な露出機会を見つけられます。',
    'advertiser.marketplace.feature1.title': '精密なフィルタリング',
    'advertiser.marketplace.feature1.desc': '地域、会場タイプ、人流特性に基づいて最適な枠をフィルタリング。',
    'advertiser.marketplace.feature2.title': '柔軟なスケジューリング',
    'advertiser.marketplace.feature2.desc': '単日、複数日、特定時間帯の配信に対応し、予算運用が柔軟に。',
    'advertiser.marketplace.feature3.title': 'ワンストップ管理',
    'advertiser.marketplace.feature3.desc': 'すべてのキャンペーンを統一バックエンドで管理、クリエイティブの変更もワンクリック。',
    'advertiser.interaction.title': '露出だけでなく、深いインタラクションも',
    'advertiser.interaction.description': 'AZIO1ADはチケットシステムと現場インタラクションモジュールを独自に統合。チケット購入フロー、電子チケット、抽選イベントに広告を組み込み、真のコンバージョンを生み出します。',
    'advertiser.interaction.list1': '電子チケット広告配置',
    'advertiser.interaction.list2': '現場QR抽選',
    'advertiser.interaction.list3': 'チケット購入フローでの追加プロモーション',
    'advertiser.interaction.list4': 'リアルタイムインタラクティブゲーム',
    'advertiser.interaction.button': 'インタラクティブモジュールを試す',
    'advertiser.cta.title': 'ブランド露出を高める準備はできましたか？',
    'advertiser.cta.description': '今すぐAZIO1AD広告主アカウントを登録し、初回キャンペーンの限定特典を受け取りましょう。',
    'advertiser.cta.button': '無料広告主登録',

    // Media Owner Page
    'mediaOwner.hero.badge': 'メディアオーナー向け',
    'mediaOwner.hero.title.1': '遊休スクリーンを',
    'mediaOwner.hero.title.2': 'キャッシュフローへ',
    'mediaOwner.hero.description': '展示場、ショッピングモール、イベント会場など。AZIO1ADは、場所のスクリーンを収益化可能なメディア資産に変え、簡単に管理し、自動的に利益を生み出すお手伝いをします。',
    'mediaOwner.hero.cta': 'メディアパートナーになる',
    'mediaOwner.stats.monthly': '月間推定収益',
    'mediaOwner.stats.growth': '成長の可能性',
    'mediaOwner.stats.rental': '広告枠レンタル',
    'mediaOwner.stats.promotion': '自社プロモーション',
    'mediaOwner.benefits.title': 'なぜAZIO1ADメディアエコシステムに参加するのか？',
    'mediaOwner.benefits.description': 'デバイス管理と広告販売におけるすべての課題を解決するワンストップSaaSソリューションを提供します。',
    'mediaOwner.benefits.card1.title': '資産の収益化',
    'mediaOwner.benefits.card1.desc': 'デジタルサイネージを公開市場にリストし、広告主と直接つながり、追加の受動的収入を生み出します。',
    'mediaOwner.benefits.card2.title': '自動管理',
    'mediaOwner.benefits.card2.desc': '統合クラウドバックエンド制御。広告スケジュール、クリエイティブ審査、再生監視はすべて自動化されています。',
    'mediaOwner.benefits.card3.title': '脱仲介化',
    'mediaOwner.benefits.card3.desc': '価格決定権と顧客リストを取り戻しましょう。ブローカーへの高額な手数料はなくなり、収益を最大化します。',
    'mediaOwner.dashboard.badge': '強力なバックエンドシステム',
    'mediaOwner.dashboard.title.1': '一つのダッシュボードで、',
    'mediaOwner.dashboard.title.2': 'すべてのスクリーンと収益を管理',
    'mediaOwner.dashboard.description': '施設オーナー向けに設計されたSaaS管理システム。スクリーンが1台でも100台でも、コンテンツ配信と収益管理を簡単に行えます。',
    'mediaOwner.dashboard.feature1': '複数施設の一元管理',
    'mediaOwner.dashboard.feature2': 'リアルタイムコンテンツ挿入',
    'mediaOwner.dashboard.feature3': '収益レポート分析',
    'mediaOwner.dashboard.feature4': 'カスタム審査メカニズム',
    'mediaOwner.revenue.title.1': '多様な収益化モデル、',
    'mediaOwner.revenue.title.2': '第二の成長曲線を描く',
    'mediaOwner.revenue.description': '単なる広告枠レンタルを超えて、AZIO1ADはより多様な収益機会を提供します。チケットシステムやインタラクティブモジュールを統合し、場所の価値を高めます。',
    'mediaOwner.revenue.card1.title': 'スペースレンタル収益',
    'mediaOwner.revenue.card1.desc': '価格と枠を自由に設定し、広告主に開放して安定した賃料を得ることができます。',
    'mediaOwner.revenue.card2.title': 'インタラクティブモジュール追加',
    'mediaOwner.revenue.card2.desc': '抽選やゲームなどのインタラクティブ機能を広告主に追加提供し、客単価を向上させます。',
    'mediaOwner.revenue.card3.title': 'データレポート販売',
    'mediaOwner.revenue.card3.desc': '施設の人流とオーディエンス分析を高価値なデータレポートに変換します。',
    'mediaOwner.cta.title': 'あなたの場所にはもっと価値がある',
    'mediaOwner.cta.description': 'AZIO1ADに参加して、今すぐ場所のデジタルトランスフォーメーションの旅を始めましょう。',
    'mediaOwner.cta.button.apply': 'メディアパートナーに申請',
    'mediaOwner.cta.button.download': '資料をダウンロード',

    // Pricing Page
    'pricing.hero.title.1': '最適なプランを選んで、',
    'pricing.hero.title.2': '場所の収益化を始めましょう',
    'pricing.hero.description': '単一店舗から大型展示場まで、AZIO1ADはあなたに合ったソリューションを提供します。無料体験から完全なエコシステム統合まで、スクリーンの価値を最大化します。',
    'pricing.plan.trial.name': '体験版',
    'pricing.plan.trial.desc': '個人テストや小規模な場所での体験に最適',
    'pricing.plan.trial.cta': '無料で開始',
    'pricing.plan.business.name': 'ビジネス版',
    'pricing.plan.business.desc': '中小規模の場所に最適、すぐに広告収益化を開始',
    'pricing.plan.business.cta': '今すぐ登録',
    'pricing.plan.business.popular': '一番人気',
    'pricing.plan.flagship.name': 'フラッグシップ版',
    'pricing.plan.flagship.desc': '大型展示場やチェーンブランド向け、完全なエコシステム統合',
    'pricing.plan.flagship.price': 'お問い合わせ',
    'pricing.plan.flagship.cta': 'お問い合わせ',
    'pricing.feature.link1': '再生リンク 1組',
    'pricing.feature.link5': '再生リンク 5組',
    'pricing.feature.linkUnlimited': '再生リンク 無制限',
    'pricing.feature.scheduleBasic': '基本クラウドスケジュール',
    'pricing.feature.scheduleAdvanced': '高度なクラウドスケジュール',
    'pricing.feature.scheduleMulti': '多階層権限管理',
    'pricing.feature.qualityStandard': '標準画質出力',
    'pricing.feature.qualityHD': 'HD画質出力',
    'pricing.feature.quality4K': '4K超高画質出力',
    'pricing.feature.watermark': '透かし入り出力',
    'pricing.feature.noWatermark': '公式透かし削除',
    'pricing.feature.adSpace': '広告枠掲載権限',
    'pricing.feature.adPriority': '広告枠優先露出',
    'pricing.feature.interactive': 'インタラクティブモジュール (抽選/ゲーム)',
    'pricing.feature.api': 'API連携',
    'pricing.feature.apiPos': 'API連携 (チケット/POS)',
    'pricing.feature.reportBasic': '基本データレポート',
    'pricing.faq.title': 'よくある質問',
    'pricing.faq.q1': '「再生リンク」とは何ですか？',
    'pricing.faq.a1': '再生リンクはAZIO1ADシステムが生成する専用URLです。このURLをインターネットに接続されたスクリーン（スマートTV、タブレット、デジタルサイネージなど）のブラウザに入力するだけで、追加のハードウェアなしで設定した広告コンテンツの再生を開始できます。',
    'pricing.faq.q2': '体験版に利用期限はありますか？',
    'pricing.faq.a2': '現在、体験版に厳密な利用期限は設けていません。システムの安定性や操作インターフェースを存分にテストしていただけます。ただし、体験版の出力画面にはAZIO1ADの透かしが入り、広告収益化機能は利用できませんのでご注意ください。',
    'pricing.faq.q3': '広告マーケットプレイスで収益を得るには？',
    'pricing.faq.a3': '「ビジネス版」または「フラッグシップ版」を購読後、バックエンドでスクリーンの枠情報（場所、人流、サイズなど）を設定できます。審査通過後、あなたの枠はAZIO1AD広告マーケットプレイスに掲載され、広告主が購入できるようになります。広告主が注文すると、収益分配を受け取ることができます。',
    'pricing.faq.q4': 'いつでもアップグレードや解約ができますか？',
    'pricing.faq.a4': 'はい、バックエンドでいつでもプランをアップグレードでき、新機能は即座に有効になります。解約を決定された場合、サービスは現在の請求サイクルの終了まで継続されます。',
    'pricing.cta.title': 'どのプランが適しているかわかりませんか？',
    'pricing.cta.description': '専門のコンサルティングチームがいつでもお手伝いします。場所の規模やニーズをお知らせいただければ、最適な導入プランをご提案します。',
    'pricing.cta.button.consult': '専門家に相談予約',
    'pricing.cta.button.learnMore': 'メディアのメリットをもっと知る',

    // Features Page
    'features.hero.title': '注文してすぐに再生される広告',
    'features.hero.description': 'AZIO1ADは、広告掲載をECのように簡単にするシステムです。メディア登録、枠選択、注文支払いからスケジュール再生まで、すべて単一のプラットフォームで完了します。',
    'features.card1.title': 'メディアと枠の登録管理',
    'features.card1.subtitle': 'スクリーンを販売可能なメディア商品に変える',
    'features.card1.desc1': '施設側でメディアページ（会場/スペース/スクリーン）を独自に作成可能',
    'features.card1.desc2': '枠の仕様、サイズ、再生時間を明確に設定',
    'features.card1.desc3': '複数スクリーン、複数施設の集中管理に対応',
    'features.card1.desc4': '即時公開、いつでも調整可能、手動見積もり不要',
    'features.card1.target': '対象：展示場、ショッピングモール、イベント会場、交通ハブ',
    'features.card2.title': '広告枠マーケットプレイス',
    'features.card2.subtitle': '商品を選ぶように広告枠を選ぶ',
    'features.card2.desc1': '広告主はすべての掲載可能な枠を直接閲覧可能',
    'features.card2.desc2': '場所、時間、価格ですばやくフィルタリング',
    'features.card2.desc3': '各枠の情報は透明で、往復の問い合わせ不要',
    'features.card2.desc4': '代理店や仲介業者を通さず、直接マッチング',
    'features.card2.highlight': '👉 脱仲介化、価格とリソースの完全透明化',
    'features.card3.title': '即時注文とスケジュール再生',
    'features.card3.subtitle': '注文完了、システムが自動で再生',
    'features.card3.desc1': 'オンライン注文、手動確認不要',
    'features.card3.desc2': 'システムがスケジュールと再生設定を自動完了',
    'features.card3.desc3': '指定日、時間帯、ローテーションルールに対応',
    'features.card3.desc4': '広告コンテンツは即座に更新・差し替え可能',
    'features.card3.highlight': '真の即時性：注文≠待機、すぐに反映',
    'features.card4.title': '再生監視とステータスフィードバック',
    'features.card4.subtitle': 'すべての広告のステータスが見える',
    'features.card4.desc1': 'リアルタイム表示：再生中 / 完了 / スケジュール済み',
    'features.card4.desc2': '施設とスクリーンの状態が一目瞭然',
    'features.card4.desc3': 'コミュニケーションコストと手動照合を削減',
    'features.card5.title': 'データと効果追跡（開発中）',
    'features.card5.subtitle': '広告をただ流すだけでなく、見られるものに',
    'features.card5.desc1': '再生ログを完全に保存',
    'features.card5.desc2': '人流 / チケットデータとの連携（プランによる）',
    'features.card5.desc3': '将来の配信最適化と価格設定の根拠に',
    'features.card6.title': '権限と役割管理',
    'features.card6.subtitle': '施設側と広告主、それぞれの業務に集中',
    'features.card6.desc1': '施設側：メディア、在庫、収益の管理',
    'features.card6.desc2': '広告主：枠選択、注文、入稿、成果確認',
    'features.card6.desc3': '明確な権限分離、ワークフローの競合なし',
    'features.why.title': 'なぜAZIO1ADを選ぶのか？',
    'features.why.description': 'AZIO1ADは、広告を直接注文し、すぐに再生できるシステムです。',
    'features.why.reason1': '広告掲載プロセスを完全オンライン化',
    'features.why.reason2': '価格、枠、再生の完全透明化',
    'features.why.reason3': '仲介なし、コミュニケーション削減、省力化',
    'features.why.reason4': '「再生ツール」から「取引プラットフォーム」へ進化',
    'features.cta.title': '新しい広告掲載モデルを体験する準備はできましたか？',
    'features.cta.description': '施設オーナーでも広告主でも、AZIO1ADはあなたに新しい価値を創造します。',
    'features.cta.button.trial': '無料トライアルを開始',
    'features.cta.button.demo': 'デモを予約',

    // Case Studies Page
    'caseStudies.hero.title': '導入事例',
    'caseStudies.hero.description': '他の施設オーナーや広告主がAZIO1ADを通じてどのように価値を創造しているかをご覧ください。',
    'caseStudies.card1.title': '南港展覧館',
    'caseStudies.card1.category': '展示場',
    'caseStudies.card1.description': 'AZIO1ADデジタルサイネージ管理システムを通じて、遊休スクリーンを高収益の広告枠に転換し、管理コストを大幅に削減しました。',
    'caseStudies.card2.title': '信義区ショッピングエリア',
    'caseStudies.card2.category': 'ショッピングモール',
    'caseStudies.card2.description': '複数の屋外大型看板を統合し、ブランド主にワンストップの配信サービスを提供。プロモーション情報をリアルタイムで更新し、コンバージョン率を向上。',
    'caseStudies.card3.title': '全国チェーン映画館',
    'caseStudies.card3.category': 'エンターテインメント施設',
    'caseStudies.card3.description': '待ち時間を利用して正確な映画予告編や関連商品の広告を配信し、追加収益を生み出しつつ、観客体験を向上させました。',
    'caseStudies.cta.title': 'あなたの場所でも同様の価値を創造できます',
    'caseStudies.cta.description': 'AZIO1ADに参加して、今すぐ会場のデジタルトランスフォーメーションの旅を始めましょう。',
    'caseStudies.cta.primary': 'メディアパートナーになる',
    'caseStudies.cta.secondary': '私は広告主です',
    'caseStudies.cta.button': 'お問い合わせ',
    'caseStudies.nangang.subtitle': '：完全に透明なデジタル広告市場の構築',
    'caseStudies.nangang.feature1.title': 'クラウド管理',
    'caseStudies.nangang.feature1.desc': 'すべてのキャンペーンを統一バックエンドで管理',
    'caseStudies.nangang.feature2.title': 'レンタル収益',
    'caseStudies.nangang.feature2.desc': '価格と枠を設定し、購入可能にする',
    'caseStudies.nangang.feature3.title': '仲介排除',
    'caseStudies.nangang.feature3.desc': '価格決定権と顧客リストを取り戻す',
    'caseStudies.nangang.button': 'もっと詳しく',

    // About Page
   'about.hero.title': '人と空間をつなぐスマートな架け橋',
    'about.hero.company': '智林国際株式会社',
    'about.hero.description': 'AZIO1ADは、包括的な会場メディアエコシステムの構築に尽力し、テクノロジーを通じてすべての会場がその価値を最大化できるよう支援します。',
    'about.evolution.title': 'チケットから広告への進化',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': 'AZIO1は<strong>AZIO1チケットシステム</strong>から始まり、大規模イベントや会場のチケットソリューションを深く掘り下げ、豊富な人流データと会場運営経験を蓄積しました。',
    'about.evolution.p2': 'サービス提供の中で、会場には有効活用されていない巨大な「アテンション資産」が存在することを発見しました。従来の看板広告はデータによる裏付けがなく、ターゲット層に正確にリーチできませんでした。',
    'about.evolution.p3': 'そこで、チケットシステムの人流データと広告配信を組み合わせ、<strong>AZIO1AD広告システム</strong>が誕生しました。これは単なる広告プラットフォームではなく、人、データ、会場を統合したスマートエコシステムです。',
    'about.ecosystem.title': '3つの事業エコシステム',
    'about.ecosystem.description': 'AZIO1はデータを核として、チケット、広告、Eコマースをつなぎ、包括的なビジネスループを構築します。',
    'about.ecosystem.azio1.subtitle': 'チケットシステム',
    'about.ecosystem.azio1.description': '購入、検証、入場管理のワンストップサービスを提供するプロフェッショナルなチケットソリューションで、核心的な人流データを把握します。',
    'about.ecosystem.azio1ad.subtitle': '広告システム',
    'about.ecosystem.azio1ad.description': '統合型オンサイト広告配信・管理SaaS。人流を広告価値に変え、精密なマーケティングを実現します。',
    'about.ecosystem.azio1ec.subtitle': 'Eコマースシステム',
    'about.ecosystem.azio1ec.description': 'Bサイドクライアントのオンライン商取引を支援し、システムツールとコンサルティングサービスを提供して、独自のブランド販売チャネルを構築します。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.innovation.title': '革新 Innovation',
    'about.values.innovation.description': '新しい技術を継続的に探求し、会場メディアにさらなる可能性をもたらします。',
    'about.values.integration.title': '統合 Integration',
    'about.values.integration.description': 'チケット、広告、Eコマースをつなぎ、シームレスなビジネス体験を創出します。',
    'about.values.winwin.title': '共存共栄 Win-Win',
    'about.values.winwin.description': '会場オーナーや広告主と価値を共有し、長期的なパートナーシップを築きます。',
    'about.cta.title': 'あなたの会場には、もっと価値がある',
    'about.cta.description': 'AZIO1ADに参加して、今すぐ会場のデジタルトランスフォーメーションの旅を始めましょう。',
    'about.cta.primary': 'メディアパートナーになる',
    'about.cta.secondary': '私は広告主です',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('zh');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['zh', 'en', 'ja'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    const value = translations[language][key];
    if (value === undefined) {
      // In development, throw an error to force a fix.
      // In production, fallback to the key to avoid crashing the user's experience (though ideally this shouldn't happen if dev catches it).
      if (import.meta.env.DEV) {
        throw new Error(`Missing translation key: "${key}" for language: "${language}"`);
      }
      console.error(`Missing translation key: "${key}" for language: "${language}"`);
      return key;
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
