import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.features': '產品功能',
    'nav.solutions': '解決方案',
    'nav.pricing': '定價方案',
    'nav.caseStudies': '客戶案例',
    'nav.about': '關於我們',
    'nav.advertiser': '我是廣告主',
    'nav.advertiser.desc': '買廣告，精準投放目標場域',
    'nav.mediaOwner': '我是媒體方',
    'nav.mediaOwner.desc': '賣版位，閒置螢幕變現',
    'nav.freeTrial': '免費試用',

    // Footer
    'footer.product': '產品',
    'footer.company': '公司',
    'footer.legal': '法律',
    'footer.contact': '聯絡我們',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': '隱私權政策',
    'footer.terms': '服務條款',

    // Home
    'home.hero.title': '智映媒體\n交易管理系統',
    'home.hero.subtitle': 'AZIO1AD 重新定義廣告版位的銷售與購買方式。讓每個螢幕都成為可變現的媒體資產，打造全透明、即時化的廣告交易體驗。',
    'home.hero.cta': '開始免費試用',
    'home.hero.demo': '預約專人演示',
    'home.hero.badge': '台灣首個去經銷化場域廣告 SaaS 平台',
    'home.features.security': '企業級資安防護',
    'home.features.instant': '即時上架銷售',
    'home.features.title': '為什麼選擇 AZIO1AD？',
    'home.features.subtitle': '我們打破傳統廣告採購的黑箱作業，為您帶來前所未有的透明與效率。',
    'home.features.transparency.title': '價格透明，拒絕黑箱',
    'home.features.transparency.desc': '所有版位價格公開透明，廣告主可直接線上比價下單，媒體方可自主定價，告別層層剝削。',
    'home.features.efficiency.title': '即時上架，快速變現',
    'home.features.efficiency.desc': '媒體方可隨時上架閒置螢幕，廣告主可即時查詢檔期並投放，大幅縮短交易流程。',
    'home.features.data.title': '數據驅動，精準投放',
    'home.features.data.desc': '整合人流分析與票務數據，協助廣告主精準鎖定目標受眾，提升廣告轉換成效。',
    'home.cta.title': '準備好開始了嗎？',
    'home.cta.subtitle': '立即加入 AZIO1AD，體驗全新的廣告交易模式。',
    'home.cta.advertiser': '我是廣告主',
    'home.cta.mediaOwner': '我是媒體方',

    // Advertiser
    'advertiser.hero.title': '精準投放，\n觸及真實受眾',
    'advertiser.hero.subtitle': '告別無效曝光。AZIO1AD 讓您直接對接全台優質場域，用數據驅動每一分預算，極大化廣告效益。',
    'advertiser.hero.badge': '廣告主專屬',
    'advertiser.why.title': '為什麼選擇 AZIO1AD？',
    'advertiser.why.description': '我們提供的不僅是廣告版位，更是與消費者深度連結的機會。',
    'advertiser.why.card1.title': '精準場域鎖定',
    'advertiser.why.card1.desc': '依據場域類型（展覽、商辦、零售）與人流特徵，精準鎖定您的目標客群。',
    'advertiser.why.card2.title': '價格公開透明',
    'advertiser.why.card2.desc': '直接查看版位價格與檔期，免去繁瑣詢價過程，預算控管更精準。',
    'advertiser.why.card3.title': '互動行銷模組',
    'advertiser.why.card3.desc': '支援抽獎、問卷等互動模組，將被動觀看轉化為與品牌的主動互動。',
    'advertiser.marketplace.badge.status': '狀態',
    'advertiser.marketplace.badge.active': '已上線',
    'advertiser.marketplace.title.1': '廣告庫存',
    'advertiser.marketplace.title.2': '市集',
    'advertiser.marketplace.description': '像網購一樣簡單地購買廣告。瀏覽全台優質版位，透明價格，即時下單。',
    'advertiser.marketplace.feature1.title': '透明價格',
    'advertiser.marketplace.feature1.desc': '所有版位價格公開透明，無隱藏費用。',
    'advertiser.marketplace.feature2.title': '即時檔期',
    'advertiser.marketplace.feature2.desc': '即時查看版位可售檔期，立即預訂。',
    'advertiser.marketplace.feature3.title': '線上支付',
    'advertiser.marketplace.feature3.desc': '支援多種線上支付方式，快速完成交易。',
    'advertiser.interaction.title': '票務與互動整合',
    'advertiser.interaction.description': '結合 AZIO1 票務系統，將廣告延伸至購票流程與現場互動，創造更多接觸點。',
    'advertiser.interaction.list.1': '購票頁面廣告',
    'advertiser.interaction.list.2': '電子票券廣告',
    'advertiser.interaction.list.3': '現場抽獎互動',
    'advertiser.interaction.list.4': '問卷調查收集',
    'advertiser.interaction.cta': '了解更多互動方案',
    'advertiser.cta.button': '開始免費試用',
    'advertiser.features.title': '不只是曝光，還能深度互動',
    'advertiser.features.subtitle': '我們提供的不僅是廣告版位，更是與消費者深度連結的機會。',
    'advertiser.features.precise.title': '精準場域鎖定',
    'advertiser.features.precise.desc': '依據場域類型（展覽、商辦、零售）與人流特徵，精準鎖定您的目標客群。',
    'advertiser.features.transparent.title': '價格公開透明',
    'advertiser.features.transparent.desc': '直接查看版位價格與檔期，免去繁瑣詢價過程，預算控管更精準。',
    'advertiser.features.interactive.title': '互動行銷模組',
    'advertiser.features.interactive.desc': '支援抽獎、問卷等互動模組，將被動觀看轉化為與品牌的主動互動。',
    'advertiser.steps.title': '簡單三步驟，開始投放',
    'advertiser.steps.1.title': '搜尋版位',
    'advertiser.steps.1.desc': '依據地區、場域類型篩選適合的廣告版位。',
    'advertiser.steps.2.title': '線上預訂',
    'advertiser.steps.2.desc': '確認檔期與價格，直接線上完成預訂與付款。',
    'advertiser.steps.3.title': '上傳素材',
    'advertiser.steps.3.desc': '上傳廣告素材，系統自動審核後即刻上線。',
    'advertiser.cta.title': '準備好開始投放了嗎？',
    'advertiser.cta.description': '立即註冊帳號，瀏覽全台優質廣告版位。',
    'advertiser.cta.button.start': '開始免費試用',
    'advertiser.cta.button.demo': '預約專人演示',

    // Media Owner
    'media.hero.title': '閒置螢幕，\n變身獲利資產',
    'media.hero.subtitle': '無需繁瑣業務開發。AZIO1AD 協助您將場域螢幕上架銷售，自動媒合廣告主，輕鬆創造額外營收。',
    'media.features.title': '讓您的場域發揮最大價值',
    'media.features.subtitle': '我們提供完整的管理工具，讓您輕鬆管理螢幕與廣告訂單。',
    'media.features.management.title': '雲端螢幕管理',
    'media.features.management.desc': '透過雲端後台，隨時隨地管理多個場域的螢幕內容與播放排程。',
    'media.features.sales.title': '自動化銷售',
    'media.features.sales.desc': '設定版位價格與可售時段，系統自動媒合廣告主訂單，無需人工介入。',
    'media.features.report.title': '收益報表分析',
    'media.features.report.desc': '即時查看廣告收益與播放數據，掌握場域營運狀況，優化定價策略。',
    'media.steps.title': '輕鬆啟用，立即變現',
    'media.steps.1.title': '註冊場域',
    'media.steps.1.desc': '填寫場域資訊與螢幕規格，完成帳號註冊。',
    'media.steps.2.title': '安裝播放器',
    'media.steps.2.desc': '將 AZIO1AD 播放器安裝至您的螢幕設備。',
    'media.steps.3.title': '開始獲利',
    'media.steps.3.desc': '設定可售時段與價格，等待廣告主下單獲取收益。',
    'mediaOwner.hero.badge': '媒體方專屬',
    'mediaOwner.hero.title.1': '讓閒置螢幕，',
    'mediaOwner.hero.title.2': '變成現金流',
    'mediaOwner.hero.description': '無論是展覽館、商場還是活動場地。AZIO1AD 協助您將場域螢幕轉化為可變現的媒體資產，輕鬆管理、自動獲利。',
    'mediaOwner.hero.cta': '成為媒體合作夥伴',
    'mediaOwner.stats.title': '預估每月收益',
    'mediaOwner.stats.growth': '成長潛力',
    'mediaOwner.stats.rent': '廣告版位出租',
    'mediaOwner.stats.self': '自營內容推廣',
    'mediaOwner.why.title': '為什麼加入 AZIO1AD 媒體生態系？',
    'mediaOwner.why.description': '我們提供一站式 SaaS 解決方案，解決您在設備管理與廣告招商上的所有痛點。',
    'mediaOwner.why.card1.title': '資產變現',
    'mediaOwner.why.card1.desc': '將場域內的數位看板上架至公開市場，直接對接廣告主，創造額外被動收入。',
    'mediaOwner.why.card2.title': '自動化管理',
    'mediaOwner.why.card2.desc': '雲端後台統一控管所有螢幕。廣告排程、素材審核、播放監控，全部自動化完成。',
    'mediaOwner.why.card3.title': '去經銷化',
    'mediaOwner.why.card3.desc': '拿回定價權與客戶名單。不再被經銷商抽取高額佣金，實現收益最大化。',
    'mediaOwner.dashboard.badge': '強大的後台系統',
    'mediaOwner.dashboard.title.1': '一個後台，',
    'mediaOwner.dashboard.title.2': '掌控所有螢幕與收益',
    'mediaOwner.dashboard.description': '專為場域主設計的 SaaS 管理系統。無論您擁有 1 個還是 100 個螢幕，都能輕鬆進行內容派送與營收管理。',
    'mediaOwner.dashboard.feature1': '多場域集中管理',
    'mediaOwner.dashboard.feature2': '即時內容插播',
    'mediaOwner.dashboard.feature3': '收益報表分析',
    'mediaOwner.dashboard.feature4': '自訂審核機制',
    'mediaOwner.revenue.title.1': '多元變現模式，',
    'mediaOwner.revenue.title.2': '創造第二成長曲線',
    'mediaOwner.revenue.description': '除了單純的廣告版位出租，AZIO1AD 還提供更多元的獲利機會。結合票務系統與互動模組，提升場域價值。',
    'mediaOwner.revenue.item1.title': '版位出租收益',
    'mediaOwner.revenue.item1.desc': '自訂價格與時段，開放廣告主購買，獲取穩定租金。',
    'mediaOwner.revenue.item2.title': '互動模組加購',
    'mediaOwner.revenue.item2.desc': '提供抽獎、遊戲等互動功能供廣告主加購，提高客單價。',
    'mediaOwner.revenue.item3.title': '數據報告銷售',
    'mediaOwner.revenue.item3.desc': '將場域人流與受眾分析轉化為高價值的數據報告。',
    'mediaOwner.cta.title': '您的場域，值得更多價值',
    'mediaOwner.cta.description': '加入 AZIO1AD，立即開啟您的場域數位轉型之旅。',
    'mediaOwner.cta.button.apply': '申請成為媒體夥伴',
    'mediaOwner.cta.button.download': '下載合作簡報',

    // Pricing
    'pricing.title': '簡單透明的定價方案',
    'pricing.subtitle': '無論您是剛起步的小型場域，還是擁有多個據點的大型企業，我們都有適合您的方案。',
    'pricing.advertiser.title': '廣告主',
    'pricing.advertiser.desc': '免費註冊，僅需支付廣告費用',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ 月',
    'pricing.advertiser.feature1': '瀏覽全台優質版位',
    'pricing.advertiser.feature2': '價格透明，線上比價',
    'pricing.advertiser.feature3': '即時投放，成效追蹤',
    'pricing.advertiser.feature4': '基本數據報表',
    'pricing.media.starter.title': '媒體方 - 體驗版',
    'pricing.media.starter.desc': '適合單一場域或少量螢幕',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ 月',
    'pricing.media.starter.feature1': '管理 1 個場域',
    'pricing.media.starter.feature2': '最多 3 個螢幕',
    'pricing.media.starter.feature3': '基本排程管理',
    'pricing.media.starter.feature4': '5% 平台服務費',
    'pricing.media.pro.title': '媒體方 - 專業版',
    'pricing.media.pro.desc': '適合多場域或連鎖企業',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ 月 / スクリーン',
    'pricing.media.pro.feature1': '無制限の場所管理',
    'pricing.media.pro.feature2': '無制限のスクリーン数',
    'pricing.media.pro.feature3': '高度なスケジュールとインタラクション',
    'pricing.media.pro.feature4': '3% プラットフォーム手数料',
    'pricing.enterprise.title': 'エンタープライズ',
    'pricing.enterprise.desc': '大規模な場所または特別なニーズ向け',
    'pricing.enterprise.price': 'カスタム',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': '専用API連携',
    'pricing.enterprise.feature2': 'カスタム機能開発',
    'pricing.enterprise.feature3': '専用サポート',
    'pricing.enterprise.feature4': '割引プラットフォーム手数料',
    'pricing.cta': '今すぐ始める',
    'pricing.contact': 'お問い合わせ',
    'pricing.header.title.1': 'あなたに合ったプランを選んで、',
    'pricing.header.title.2': '収益化の旅を始めましょう',
    'pricing.header.description': '単一の店舗でも大規模な展示会場でも、AZIO1ADにはソリューションがあります。無料トライアルから完全なエコシステム統合まで、スクリーンの価値を最大化するのを支援します。',
    'pricing.plan.trial.name': 'トライアル',
    'pricing.plan.trial.desc': '個人的なテストや小規模な場所の体験向け',
    'pricing.plan.business.name': 'ビジネス',
    'pricing.plan.business.desc': '中小規模の場所向け、すぐに収益化を開始',
    'pricing.plan.flagship.name': 'フラッグシップ',
    'pricing.plan.flagship.desc': '大規模な場所やチェーン向け、完全なエコシステム統合',
    'pricing.period.month': '/ 月',
    'pricing.feature.1link': '1 再生リンク',
    'pricing.feature.basicSchedule': '基本クラウドスケジュール',
    'pricing.feature.sd': '標準画質出力',
    'pricing.feature.watermark': '透かし入り出力',
    'pricing.feature.adListing': '廣告枠掲載権限',
    'pricing.feature.interaction': 'インタラクティブモジュール',
    'pricing.feature.api': 'API連携',
    'pricing.feature.5links': '5 再生リンク',
    'pricing.feature.advancedSchedule': '高度なクラウドスケジュール',
    'pricing.feature.hd': 'HD出力',
    'pricing.feature.noWatermark': '公式透かしなし',
    'pricing.feature.basicReport': '基本データレポート',
    'pricing.feature.unlimitedLinks': '無制限の再生リンク',
    'pricing.feature.multiLevel': '多層権限管理',
    'pricing.feature.4k': '4K超高画質出力',
    'pricing.feature.priority': '廣告枠優先露出',
    'pricing.feature.apiFull': '完全なAPI連携 (チケット/POS)',
    'pricing.cta.start': '無料で開始',
    'pricing.cta.subscribe': '今すぐ購読',
    'pricing.cta.contact': 'お問い合わせ',
    'pricing.price.contact': '相談',
    'pricing.badge.popular': '一番人気',
    'pricing.faq.title': 'よくある質問',
    'pricing.faq.q1': '「再生リンク」とは何ですか？',
    'pricing.faq.a1': '再生リンクは、AZIO1ADシステムによって生成される固有のURLです。このURLを接続されたスクリーン（スマートTV、タブレット、デジタルサイネージなど）のブラウザに入力するだけで、設定した広告コンテンツの再生を開始できます。追加のハードウェアは必要ありません。',
    'pricing.faq.q2': 'トライアル版に有効期限はありますか？',
    'pricing.faq.a2': 'トライアル版には現在、厳密な有効期限はありません。システムの安定性と操作インターフェースを好きなだけテストできます。ただし、トライアル出力にはAZIO1ADの透かしが入り、広告収益化機能は使用できないことに注意してください。',
    'pricing.faq.q3': '広告マーケットプレイスから収益を得るにはどうすればよいですか？',
    'pricing.faq.a3': '「ビジネス」または「フラッグシップ」プランに登録した後、バックエンドでスクリーン在庫情報（場所、人流、サイズ）を設定できます。承認されると、在庫はAZIO1AD広告マーケットプレイスに掲載され、広告主が購入できるようになります。広告主が注文すると、収益分配を得ることができます。',
    'pricing.faq.q4': 'いつでもアップグレードまたはキャンセルできますか？',
    'pricing.faq.a4': 'はい、バックエンドでいつでもプランをアップグレードでき、新機能はすぐに有効になります。購読をキャンセルする場合、サービスは現在の請求サイクルの終了まで継続されます。',
    'pricing.cta.title': 'どのプランが適しているかわかりませんか？',
    'pricing.cta.description': '私たちの専門コンサルティングチームがいつでもお手伝いします。場所の規模とニーズをお知らせいただければ、最適な導入計画をご提案します。',
    'pricing.cta.button.consult': '相談を予約',
    'pricing.cta.button.learnMore': 'メディアオーナーのメリットをもっと知る',

    // About
    'about.hero.title': '關於我們',
    'about.hero.subtitle': 'AZIO1AD 致力於透過科技創新，打造公平、透明、高效的場域廣告生態系。',
    'about.mission.title': '我們的使命',
    'about.mission.desc': '讓每一個螢幕都能發揮價值，讓每一次投放都能精準觸達。我們相信，透過數位轉型與數據賦能，可以打破傳統廣告市場的資訊不對稱，創造媒體方、廣告主與消費者的三贏局面。',
    'about.vision.title': '我們的願景',
    'about.vision.desc': '成為亞洲領先的場域廣告交易平台，連結實體空間與數位廣告，定義未來的家外媒體（DOOH）標準。',
    'about.team.title': '我們的團隊',
    'about.team.desc': '我們是一群來自廣告科技、軟體開發與商業顧問領域的專業人才，擁有豐富的產業經驗與創新熱情。',
    'about.hero.company': '智林國際股份有限公司',
    'about.hero.description': '我們致力於透過科技創新，整合線上與線下資源，為企業與消費者創造無縫的數位體驗。',
    'about.evolution.title': '從票務到廣告的演進',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': '智林國際起步於 <strong>AZIO1 票務系統</strong>，我們深耕於大型活動與場館的票務解決方案，累積了豐富的人流數據與場域運營經驗。',
    'about.evolution.p2': '在服務過程中，我們發現場域中存在著巨大的「注意力資產」未被有效利用。傳統的廣告看板缺乏數據支持，無法精準觸及目標受眾。',
    'about.evolution.p3': '於是，我們將票務系統的人流數據與廣告投放結合，誕生了 <strong>AZIO1AD 廣告系統</strong>。這不僅是一個廣告投放平台，更是一個整合了人流、數據與場域的智慧生態系。',
    'about.pillars.title': '三大事業體生態系',
    'about.pillars.description': 'AZIO1 以數據為核心，串聯票務、廣告與電商，打造全方位的商業閉環。',
    'about.pillars.card1.subtitle': '票務系統',
    'about.pillars.card1.desc': '專業的票務解決方案，提供購票、驗票、入場管理一站式服務，掌握核心人流數據。',
    'about.pillars.card2.subtitle': '廣告系統',
    'about.pillars.card2.desc': '整合式場域廣告投放與管理 SaaS，將人流轉化為廣告價值，實現精準行銷。',
    'about.pillars.card3.subtitle': '電商系統',
    'about.pillars.card3.desc': '協助 B 端客戶完成線上商務化，提供系統工具與顧問服務，建立自有品牌銷售管道。',
    'about.values.title': '我們的核心價值',
    'about.values.card1.title': '創新 Innovation',
    'about.values.card1.desc': '不斷突破技術邊界，重新定義傳統商業模式。',
    'about.values.card2.title': '整合 Integration',
    'about.values.card2.desc': '串聯線上數據與線下場域，打造無縫體驗。',
    'about.values.card3.title': '共贏 Win-Win',
    'about.values.card3.desc': '為場域主、廣告主與消費者創造三方共贏的價值。',
    'about.cta.title': '準備好加入我們的生態系了嗎？',
    'about.cta.description': '無論您是場域主還是廣告主，AZIO1AD 都能為您創造新的價值。',
    'about.cta.button.mediaOwner': '我是場域主',
    'about.cta.button.advertiser': '我是廣告主',

    // Features
    'features.hero.title': '強大功能，\n滿足您的所有需求',
    'features.hero.subtitle': '從廣告投放到螢幕管理，AZIO1AD 提供全方位的解決方案。',
    'features.list.title': '核心功能一覽',
    'features.ad.management': '廣告檔期管理',
    'features.ad.management.desc': '直覺的行事曆介面，輕鬆管理各個螢幕的廣告檔期與播放內容。',
    'features.device.monitoring': '設備狀態監控',
    'features.device.monitoring.desc': '即時監控螢幕連線狀態與播放畫面，異常狀況自動通報。',
    'features.data.analytics': '數據分析報表',
    'features.data.analytics.desc': '提供詳細的播放紀錄、人流數據與收益分析，協助決策優化。',
    'features.interactive': '互動行銷模組',
    'features.interactive.desc': '內建抽獎、投票、問卷等互動功能，提升廣告參與度。',
    'features.card1.title': '媒體與版位上架管理',
    'features.card1.subtitle': '把螢幕，變成可以販售的媒體商品',
    'features.card1.desc1': '場域可自行建立媒體頁面（場館 / 空間 / 螢幕）',
    'features.card1.desc2': '清楚設定版位規格、尺寸、播放時段',
    'features.card1.desc3': '支援多螢幕、多場域集中管理',
    'features.card1.desc4': '即時上架、隨時調整，不需人工報價',
    'features.card1.target': '適合：展覽館、商場、活動場域、交通節點',
    'features.card2.title': '廣告版位市集 (Marketplace)',
    'features.card2.subtitle': '像逛商品一樣選廣告版位',
    'features.card2.desc1': '廣告主可直接瀏覽所有可投放版位',
    'features.card2.desc2': '依場域、時間、價格快速篩選',
    'features.card2.desc3': '每個版位資訊透明，不用來回詢價',
    'features.card2.desc4': '不經代理、不走經銷，直接媒合',
    'features.card2.highlight': '👉 去經銷化，價格與資源全面透明',
    'features.card3.title': '即時下單與排程播放',
    'features.card3.subtitle': '下單完成，系統自動幫你播',
    'features.card3.desc1': '線上下單，無需人工確認',
    'features.card3.desc2': '系統自動完成排程與播放設定',
    'features.card3.desc3': '支援指定日期、時段、輪播規則',
    'features.card3.desc4': '廣告內容可即時更新、替換',
    'features.card3.highlight': '真正做到：下單 ≠ 等待，而是立刻生效',
    'features.card4.title': '播放監控與狀態回饋',
    'features.card4.subtitle': '每一則廣告，都看得到狀態',
    'features.card4.desc1': '即時顯示播放中 / 已完成 / 排程中',
    'features.card4.desc2': '場域與螢幕狀態一目了然',
    'features.card4.desc3': '降低溝通成本，避免人工對帳與確認',
    'features.card5.title': '數據與成效追蹤（建構中）',
    'features.card5.subtitle': '讓廣告不只是播出去，而是被看見',
    'features.card5.desc1': '播放紀錄完整留存',
    'features.card5.desc2': '可結合人流 / 票務資料（依方案）',
    'features.card5.desc3': '作為後續優化投放與定價依據',
    'features.card6.title': '權限與角色管理',
    'features.card6.subtitle': '場域與廣告主各司其職',
    'features.card6.desc1': '場域：管理媒體、版位與收益',
    'features.card6.desc2': '廣告主：選版位、下單、上傳、看成效',
    'features.card6.desc3': '權限分流明確，流程順暢',
    'features.reason1': '廣告投放流程全面線上化',
    'features.reason2': '價格、庫存、播放全面透明',
    'features.reason3': '去經銷化，少溝通、少人力',
    'features.reason4': '從「播放工具」進化為「交易平台」',
    'features.why.title': '為什麼選擇 AZIO1AD？',
    'features.why.description': 'AZIO1AD 是一套能讓您直接下單廣告、即時播放的系統。',
    'features.cta.title': '準備好體驗全新的廣告投放模式了嗎？',
    'features.cta.description': '無論您是場域主還是廣告主，AZIO1AD 都能為您創造新的價值。',
    'features.cta.button.trial': '開始免費試用',
    'features.cta.button.demo': '預約專人演示',

    // Case Studies
    'case.hero.title': '成功案例',
    'case.hero.subtitle': '看看其他企業如何透過 AZIO1AD 創造價值。',
    'case.nangang.title': '南港展覽館',
    'case.nangang.desc': '透過導入 AZIO1AD 數位看板管理系統，將館內閒置螢幕轉化為高價值的廣告版位，成功提升非展期收益達 30%。',
    'case.retail.title': '連鎖零售店',
    'case.retail.desc': '利用 AZIO1AD 聯播網功能，統一管理全台 50 間門市的促銷內容，並將剩餘版位開放給外部品牌投放，創造額外營收。',
    'caseStudies.hero.title': '客戶案例',
    'caseStudies.hero.description': '看看領先的場域主如何透過 AZIO1AD 創造價值',
    'caseStudies.nangang.location': '台北南港展覽館',
    'caseStudies.nangang.badge': '全台最大展覽場域，數位轉型典範',
    'caseStudies.nangang.solution': '展覽場館解決方案',
    'caseStudies.nangang.title': '南港展覽館：打造全透明的數位廣告市集',
    'caseStudies.nangang.description': '南港展覽館使用 AZIO1AD 同時管理多個廣告螢幕，並用最簡單的方式銷售廣告。周邊餐廳、參展商、未參展廠商，只要註冊帳號，就能線上購買廣告版位，隨時查看空檔，價格透明，行銷預算好掌控。',
    'caseStudies.nangang.feature1.title': '多螢幕集中管理',
    'caseStudies.nangang.feature1.desc': '統一後台管理所有數位看板，即時更新內容',
    'caseStudies.nangang.feature2.title': '最大化廣告收益',
    'caseStudies.nangang.feature2.desc': '閒置時段自動轉為可銷售庫存，創造額外營收',
    'caseStudies.nangang.feature3.title': '自助式廣告投放',
    'caseStudies.nangang.feature3.desc': '廣告主自行挑選、下單、上傳，大幅降低人力成本',
    'caseStudies.nangang.cta': '了解更多場域解決方案',
    'caseStudies.cta.title': '想為您的場域創造額外營收嗎？',
    'caseStudies.cta.description': '加入 AZIO1AD 生態系，將閒置螢幕轉化為獲利的數位資產。',
    'caseStudies.cta.button.mediaOwner': '我是場域主',
    'caseStudies.cta.button.advertiser': '我是廣告主',

    // Get Started
    'getstarted.title': '選擇您的角色',
    'getstarted.subtitle': '無論您想買廣告還是賣版位，我們都能滿足您的需求。',
    'getstarted.advertiser.title': '我是廣告主',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': '我想購買廣告版位，推廣品牌或商品。',
    'getstarted.advertiser.feature1': '瀏覽優質版位',
    'getstarted.advertiser.feature2': '價格透明，線上預訂',
    'getstarted.advertiser.feature3': '即時上線，成效追蹤',
    'getstarted.advertiser.cta': '我是廣告主',
    'getstarted.media.title': '我是媒體方',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': '我想上架廣告螢幕，將流量變現。',
    'getstarted.media.feature1': '輕鬆管理多場域螢幕',
    'getstarted.media.feature2': '自訂版位與銷售價格',
    'getstarted.media.feature3': '自動排程與收益報表',
    'getstarted.media.cta': '我是媒體方',
    'getStarted.title': '準備好開始了嗎？',
    'getStarted.subtitle': '選擇您的角色，體驗 AZIO1AD 帶來的數位廣告革命。',
    'getStarted.advertiser.title': '我是廣告主',
    'getStarted.advertiser.desc': '我想購買廣告版位，推廣品牌或商品。',
    'getStarted.advertiser.feature1': '瀏覽優質版位',
    'getStarted.advertiser.feature2': '價格透明，線上預訂',
    'getStarted.advertiser.feature3': '即時上線，成效追蹤',
    'getStarted.advertiser.button': '我是廣告主',
    'getStarted.mediaOwner.title': '我是媒體方',
    'getStarted.mediaOwner.desc': '我想上架廣告螢幕，將流量變現。',
    'getStarted.mediaOwner.feature1': '輕鬆管理多場域螢幕',
    'getStarted.mediaOwner.feature2': '自訂版位與銷售價格',
    'getStarted.mediaOwner.feature3': '自動排程與收益報表',
    'getStarted.mediaOwner.button': '我是媒體方',
  },
  en: {
    // Navbar
    'nav.features': 'Features',
    'nav.solutions': 'Solutions',
    'nav.pricing': 'Pricing',
    'nav.caseStudies': 'Case Studies',
    'nav.about': 'About Us',
    'nav.advertiser': 'Advertiser',
    'nav.advertiser.desc': 'Buy ads, reach target venues',
    'nav.mediaOwner': 'Media Owner',
    'nav.mediaOwner.desc': 'Sell slots, monetize screens',
    'nav.freeTrial': 'Free Trial',

    // Footer
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Home
    'home.hero.title': 'Smart Media\nTrading System',
    'home.hero.subtitle': 'AZIO1AD redefines how ad inventory is sold and bought. Turning every screen into a monetizable media asset, creating a fully transparent, real-time ad trading experience.',
    'home.hero.cta': 'Start Free Trial',
    'home.hero.demo': 'Book Demo',
    'home.hero.badge': 'Taiwan\'s First De-intermediated DOOH SaaS Platform',
    'home.features.security': 'Enterprise Security',
    'home.features.instant': 'Instant Listing & Sales',
    'home.features.title': 'Why Choose AZIO1AD?',
    'home.features.subtitle': 'We break the black box of traditional ad purchasing, bringing you unprecedented transparency and efficiency.',
    'home.features.transparency.title': 'Transparent Pricing',
    'home.features.transparency.desc': 'All ad slot prices are public and transparent. Advertisers can compare and order directly online, media owners can set prices autonomously.',
    'home.features.efficiency.title': 'Instant Listing, Fast Monetization',
    'home.features.efficiency.desc': 'Media owners can list idle screens anytime. Advertisers can check availability and launch campaigns instantly.',
    'home.features.data.title': 'Data-Driven Targeting',
    'home.features.data.desc': 'Integrating foot traffic analytics and ticketing data to help advertisers precisely target audiences and improve conversion.',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.subtitle': 'Join AZIO1AD now and experience the new ad trading model.',
    'home.cta.advertiser': 'I am an Advertiser',
    'home.cta.mediaOwner': 'I am a Media Owner',

    // Advertiser
    'advertiser.hero.title': 'Precise Targeting,\nReach Real Audiences',
    'advertiser.hero.subtitle': 'Say goodbye to ineffective exposure. AZIO1AD connects you directly with premium venues across Taiwan, maximizing ad effectiveness with data-driven budgets.',
    'advertiser.hero.badge': 'For Advertisers',
    'advertiser.why.title': 'Why Choose AZIO1AD?',
    'advertiser.why.description': 'We provide not just ad spaces, but opportunities for deep connection with consumers.',
    'advertiser.why.card1.title': 'Precise Venue Targeting',
    'advertiser.why.card1.desc': 'Target your audience precisely based on venue type (exhibition, office, retail) and foot traffic characteristics.',
    'advertiser.why.card2.title': 'Transparent Pricing',
    'advertiser.why.card2.desc': 'View ad space prices and schedules directly, eliminating tedious inquiry processes for precise budget control.',
    'advertiser.why.card3.title': 'Interactive Marketing Modules',
    'advertiser.why.card3.desc': 'Support interactive modules like lucky draws and surveys, transforming passive viewing into active brand interaction.',
    'advertiser.marketplace.badge.status': 'Status',
    'advertiser.marketplace.badge.active': 'Active',
    'advertiser.marketplace.title.1': 'Ad Inventory',
    'advertiser.marketplace.title.2': 'Marketplace',
    'advertiser.marketplace.description': 'Buy ads as easily as online shopping. Browse premium inventory across Taiwan with transparent pricing and instant ordering.',
    'advertiser.marketplace.feature1.title': 'Transparent Pricing',
    'advertiser.marketplace.feature1.desc': 'All ad space prices are open and transparent with no hidden fees.',
    'advertiser.marketplace.feature2.title': 'Real-time Availability',
    'advertiser.marketplace.feature2.desc': 'Check ad space availability in real-time and book immediately.',
    'advertiser.marketplace.feature3.title': 'Online Payment',
    'advertiser.marketplace.feature3.desc': 'Support multiple online payment methods for quick transactions.',
    'advertiser.interaction.title': 'Ticketing & Interaction Integration',
    'advertiser.interaction.description': 'Combine with AZIO1 Ticketing System to extend ads to the ticketing process and on-site interaction, creating more touchpoints.',
    'advertiser.interaction.list.1': 'Ticketing Page Ads',
    'advertiser.interaction.list.2': 'E-ticket Ads',
    'advertiser.interaction.list.3': 'On-site Lucky Draws',
    'advertiser.interaction.list.4': 'Survey Collection',
    'advertiser.interaction.cta': 'Learn More About Interaction',
    'advertiser.cta.button': 'Start Free Trial',
    'advertiser.features.title': 'Not Just Exposure, But Deep Interaction',
    'advertiser.features.subtitle': 'We provide not just ad slots, but opportunities for deep connection with consumers.',
    'advertiser.features.precise.title': 'Precise Venue Targeting',
    'advertiser.features.precise.desc': 'Precisely target your customers based on venue type (exhibition, office, retail) and foot traffic characteristics.',
    'advertiser.features.transparent.title': 'Transparent Pricing',
    'advertiser.features.transparent.desc': 'View slot prices and schedules directly, skipping tedious inquiry processes for better budget control.',
    'advertiser.features.interactive.title': 'Interactive Marketing Modules',
    'advertiser.features.interactive.desc': 'Support interactive modules like lucky draws and surveys, turning passive viewing into active engagement with the brand.',
    'advertiser.steps.title': 'Start in 3 Simple Steps',
    'advertiser.steps.1.title': 'Search Inventory',
    'advertiser.steps.1.desc': 'Filter suitable ad slots by region and venue type.',
    'advertiser.steps.2.title': 'Book Online',
    'advertiser.steps.2.desc': 'Confirm schedule and price, complete booking and payment directly online.',
    'advertiser.steps.3.title': 'Upload Creative',
    'advertiser.steps.3.desc': 'Upload ad creatives, system auto-reviews and launches instantly.',
    'advertiser.cta.title': 'Ready to Start Advertising?',
    'advertiser.cta.description': 'Register now and browse premium ad inventory across Taiwan.',
    'advertiser.cta.button.start': 'Start Free Trial',
    'advertiser.cta.button.demo': 'Book Demo',

    // Media Owner
    'media.hero.title': 'Turn Idle Screens\nInto Profit Assets',
    'media.hero.subtitle': 'No need for tedious sales development. AZIO1AD helps you list venue screens for sale, automatically matching advertisers to easily create extra revenue.',
    'media.features.title': 'Maximize Your Venue Value',
    'media.features.subtitle': 'We provide complete management tools to help you easily manage screens and ad orders.',
    'media.features.management.title': 'Cloud Screen Management',
    'media.features.management.desc': 'Manage screen content and playback schedules for multiple venues anytime, anywhere via cloud dashboard.',
    'media.features.sales.title': 'Automated Sales',
    'media.features.sales.desc': 'Set slot prices and available times. System automatically matches advertiser orders without manual intervention.',
    'media.features.report.title': 'Revenue Reports',
    'media.features.report.desc': 'View ad revenue and playback data in real-time to grasp venue operation status and optimize pricing strategies.',
    'media.steps.title': 'Easy Setup, Instant Monetization',
    'media.steps.1.title': 'Register Venue',
    'media.steps.1.desc': 'Fill in venue info and screen specs to complete account registration.',
    'media.steps.2.title': 'Install Player',
    'media.steps.2.desc': 'Install AZIO1AD player on your screen equipment.',
    'media.steps.3.title': 'Start Earning',
    'media.steps.3.desc': 'Set available slots and prices, wait for advertisers to book and earn revenue.',
    'mediaOwner.hero.badge': 'For Media Owners',
    'mediaOwner.hero.title.1': 'Turn Idle Screens',
    'mediaOwner.hero.title.2': 'Into Cash Flow',
    'mediaOwner.hero.description': 'Whether exhibition halls, malls, or event venues. AZIO1AD helps you transform venue screens into monetizable media assets, easily managed and automatically profitable.',
    'mediaOwner.hero.cta': 'Become a Media Partner',
    'mediaOwner.stats.title': 'Est. Monthly Revenue',
    'mediaOwner.stats.growth': 'Growth Potential',
    'mediaOwner.stats.rent': 'Ad Slot Rental',
    'mediaOwner.stats.self': 'Self-Promotion',
    'mediaOwner.why.title': 'Why Join AZIO1AD Media Ecosystem?',
    'mediaOwner.why.description': 'We provide a one-stop SaaS solution to solve all your pain points in device management and ad sales.',
    'mediaOwner.why.card1.title': 'Asset Monetization',
    'mediaOwner.why.card1.desc': 'List digital signage in your venue on the public market, connect directly with advertisers, and create extra passive income.',
    'mediaOwner.why.card2.title': 'Automated Management',
    'mediaOwner.why.card2.desc': 'Unified cloud control for all screens. Ad scheduling, creative review, playback monitoring, all automated.',
    'mediaOwner.why.card3.title': 'De-intermediation',
    'mediaOwner.why.card3.desc': 'Take back pricing power and client lists. No more high commissions to brokers, maximizing revenue.',
    'mediaOwner.dashboard.badge': 'Powerful Backend System',
    'mediaOwner.dashboard.title.1': 'One Dashboard,',
    'mediaOwner.dashboard.title.2': 'Control All Screens & Revenue',
    'mediaOwner.dashboard.description': 'SaaS management system designed for venue owners. Whether you have 1 or 100 screens, easily manage content delivery and revenue.',
    'mediaOwner.dashboard.feature1': 'Multi-venue Centralized Management',
    'mediaOwner.dashboard.feature2': 'Instant Content Insertion',
    'mediaOwner.dashboard.feature3': 'Revenue Analytics Reports',
    'mediaOwner.dashboard.feature4': 'Custom Review Mechanism',
    'mediaOwner.revenue.title.1': 'Diversified Monetization,',
    'mediaOwner.revenue.title.2': 'Create Second Growth Curve',
    'mediaOwner.revenue.description': 'Beyond simple ad slot rental, AZIO1AD offers more diverse profit opportunities. Combine ticketing systems and interactive modules to increase venue value.',
    'mediaOwner.revenue.item1.title': 'Slot Rental Revenue',
    'mediaOwner.revenue.item1.desc': 'Customize prices and slots, open for advertisers to buy, earn stable rent.',
    'mediaOwner.revenue.item2.title': 'Interactive Module Add-ons',
    'mediaOwner.revenue.item2.desc': 'Provide lucky draws, games, etc. for advertisers to add on, increasing unit price.',
    'mediaOwner.revenue.item3.title': 'Data Report Sales',
    'mediaOwner.revenue.item3.desc': 'Transform venue foot traffic and audience analysis into high-value data reports.',
    'mediaOwner.cta.title': 'Your Venue Deserves More Value',
    'mediaOwner.cta.description': 'Join AZIO1AD and start your venue digital transformation journey today.',
    'mediaOwner.cta.button.apply': 'Apply as Media Partner',
    'mediaOwner.cta.button.download': 'Download Partnership Deck',

    // Pricing
    'pricing.title': 'Simple & Transparent Pricing',
    'pricing.subtitle': 'Whether you are a small venue just starting out or a large enterprise with multiple locations, we have a plan for you.',
    'pricing.advertiser.title': 'Advertiser',
    'pricing.advertiser.desc': 'Free registration, pay only for ads',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ mo',
    'pricing.advertiser.feature1': 'Browse premium inventory',
    'pricing.advertiser.feature2': 'Transparent pricing',
    'pricing.advertiser.feature3': 'Instant launch & tracking',
    'pricing.advertiser.feature4': 'Basic data reports',
    'pricing.media.starter.title': 'Media Owner - Starter',
    'pricing.media.starter.desc': 'For single venue or few screens',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ mo',
    'pricing.media.starter.feature1': 'Manage 1 venue',
    'pricing.media.starter.feature2': 'Up to 3 screens',
    'pricing.media.starter.feature3': 'Basic schedule management',
    'pricing.media.starter.feature4': '5% platform fee',
    'pricing.media.pro.title': 'Media Owner - Pro',
    'pricing.media.pro.desc': 'For multi-venue or chains',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ mo / screen',
    'pricing.media.pro.feature1': 'Unlimited venues',
    'pricing.media.pro.feature2': 'Unlimited screens',
    'pricing.media.pro.feature3': 'Advanced scheduling & interaction',
    'pricing.media.pro.feature4': '3% platform fee',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.desc': 'For large venues or special needs',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': 'Dedicated API integration',
    'pricing.enterprise.feature2': 'Custom feature development',
    'pricing.enterprise.feature3': 'Dedicated support',
    'pricing.enterprise.feature4': 'Discounted platform fee',
    'pricing.cta': 'Get Started',
    'pricing.contact': 'Contact Us',
    'pricing.header.title.1': 'Choose the Plan That Fits You,',
    'pricing.header.title.2': 'Start Your Monetization Journey',
    'pricing.header.description': 'Whether you are a single store or a large exhibition hall, AZIO1AD has a solution for you. From free trial to full ecosystem integration, helping you maximize screen value.',
    'pricing.plan.trial.name': 'Trial',
    'pricing.plan.trial.desc': 'For personal testing or small venue experience',
    'pricing.plan.business.name': 'Business',
    'pricing.plan.business.desc': 'For SMB venues, start monetizing immediately',
    'pricing.plan.flagship.name': 'Flagship',
    'pricing.plan.flagship.desc': 'For large venues and chains, full ecosystem integration',
    'pricing.period.month': '/ mo',
    'pricing.feature.1link': '1 Playback Link',
    'pricing.feature.basicSchedule': 'Basic Cloud Scheduling',
    'pricing.feature.sd': 'Standard Definition Output',
    'pricing.feature.watermark': 'Watermarked Output',
    'pricing.feature.adListing': 'Ad Inventory Listing Rights',
    'pricing.feature.interaction': 'Interactive Modules',
    'pricing.feature.api': 'API Integration',
    'pricing.feature.5links': '5 Playback Links',
    'pricing.feature.advancedSchedule': 'Advanced Cloud Scheduling',
    'pricing.feature.hd': 'HD Output',
    'pricing.feature.noWatermark': 'No Official Watermark',
    'pricing.feature.basicReport': 'Basic Data Reports',
    'pricing.feature.unlimitedLinks': 'Unlimited Playback Links',
    'pricing.feature.multiLevel': 'Multi-level Permission Management',
    'pricing.feature.4k': '4K Ultra HD Output',
    'pricing.feature.priority': 'Priority Ad Exposure',
    'pricing.feature.apiFull': 'Full API Integration (Ticketing/POS)',
    'pricing.cta.start': 'Start Free',
    'pricing.cta.subscribe': 'Subscribe Now',
    'pricing.cta.contact': 'Contact Us',
    'pricing.price.contact': 'Contact',
    'pricing.badge.popular': 'Most Popular',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'What is a "Playback Link"?',
    'pricing.faq.a1': 'A Playback Link is a unique URL generated by AZIO1AD. You simply enter this URL into the browser of any connected screen (smart TV, tablet, or digital signage) to start playing your scheduled content, no extra hardware needed.',
    'pricing.faq.q2': 'Does the Trial version expire?',
    'pricing.faq.a2': 'The Trial version currently has no hard expiration date, you can test system stability and interface as much as you like. However, please note that Trial output will have an AZIO1AD watermark and cannot use ad monetization features.',
    'pricing.faq.q3': 'How do I start earning from the Ad Marketplace?',
    'pricing.faq.a3': 'After subscribing to "Business" or "Flagship" plans, you can set up your screen inventory info (location, foot traffic, size) in the backend. Once approved, your inventory will be listed on the AZIO1AD Ad Marketplace for advertisers to purchase. You earn revenue share once an advertiser places an order.',
    'pricing.faq.q4': 'Can I upgrade or cancel anytime?',
    'pricing.faq.a4': 'Yes, you can upgrade your plan in the backend anytime, new features take effect immediately. If you decide to cancel, service continues until the end of the current billing cycle.',
    'pricing.cta.title': 'Not sure which plan fits you?',
    'pricing.cta.description': 'Our professional consulting team is ready to serve you. Tell us your venue scale and needs, and we will tailor the most suitable implementation plan for you.',
    'pricing.cta.button.consult': 'Book Consultation',
    'pricing.cta.button.learnMore': 'Learn More Media Owner Benefits',

    // About
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'AZIO1AD is dedicated to building a fair, transparent, and efficient venue advertising ecosystem through technological innovation.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To make every screen valuable and every ad reach its target precisely. We believe digital transformation and data empowerment can break information asymmetry in the traditional ad market, creating a win-win-win for media owners, advertisers, and consumers.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To become Asia\'s leading venue advertising trading platform, connecting physical spaces with digital ads, defining the future standard of DOOH.',
    'about.team.title': 'Our Team',
    'about.team.desc': 'We are a group of professionals from ad tech, software development, and business consulting, with rich industry experience and passion for innovation.',
    'about.hero.company': 'AZIO1 International Co., Ltd.',
    'about.hero.description': 'We are dedicated to integrating online and offline resources through technological innovation, creating seamless digital experiences for businesses and consumers.',
    'about.evolution.title': 'Evolution from Ticketing to Advertising',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': 'AZIO1 International started with <strong>AZIO1 Ticketing System</strong>, deeply cultivating ticketing solutions for large events and venues, accumulating rich foot traffic data and venue operation experience.',
    'about.evolution.p2': 'During our service, we discovered huge "attention assets" in venues were underutilized. Traditional billboards lacked data support and couldn\'t precisely reach target audiences.',
    'about.evolution.p3': 'Thus, we combined ticketing foot traffic data with ad delivery, birthing the <strong>AZIO1AD Advertising System</strong>. This is not just an ad platform, but a smart ecosystem integrating foot traffic, data, and venues.',
    'about.pillars.title': 'Three Business Ecosystems',
    'about.pillars.description': 'AZIO1 uses data as the core to connect ticketing, advertising, and e-commerce, creating a comprehensive business loop.',
    'about.pillars.card1.subtitle': 'Ticketing System',
    'about.pillars.card1.desc': 'Professional ticketing solutions providing one-stop service for purchasing, validation, and entry management, mastering core foot traffic data.',
    'about.pillars.card2.subtitle': 'Advertising System',
    'about.pillars.card2.desc': 'Integrated venue ad delivery and management SaaS, transforming foot traffic into ad value, achieving precision marketing.',
    'about.pillars.card3.subtitle': 'E-commerce System',
    'about.pillars.card3.desc': 'Assisting B-side clients in online commercialization, providing system tools and consulting services to build own-brand sales channels.',
    'about.values.title': 'Our Core Values',
    'about.values.card1.title': 'Innovation',
    'about.values.card1.desc': 'Constantly breaking technical boundaries, redefining traditional business models.',
    'about.values.card2.title': 'Integration',
    'about.values.card2.desc': 'Connecting online data with offline venues, creating seamless experiences.',
    'about.values.card3.title': 'Win-Win',
    'about.values.card3.desc': 'Creating win-win-win value for venue owners, advertisers, and consumers.',
    'about.cta.title': 'Ready to join our ecosystem?',
    'about.cta.description': 'Whether you are a venue owner or an advertiser, AZIO1AD can create new value for you.',
    'about.cta.button.mediaOwner': 'I am a Venue Owner',
    'about.cta.button.advertiser': 'I am an Advertiser',

    // Features
    'features.hero.title': 'Powerful Features,\nMeet All Your Needs',
    'features.hero.subtitle': 'From ad launching to screen management, AZIO1AD provides comprehensive solutions.',
    'features.list.title': 'Core Features',
    'features.ad.management': 'Ad Schedule Management',
    'features.ad.management.desc': 'Intuitive calendar interface to easily manage ad schedules and content for each screen.',
    'features.device.monitoring': 'Device Status Monitoring',
    'features.device.monitoring.desc': 'Real-time monitoring of screen connection status and playback, with automatic alerts for abnormalities.',
    'features.data.analytics': 'Data Analytics Reports',
    'features.data.analytics.desc': 'Detailed playback records, foot traffic data, and revenue analysis to help optimize decisions.',
    'features.interactive': 'Interactive Marketing',
    'features.interactive.desc': 'Built-in lucky draws, voting, surveys, and other interactive functions to increase ad engagement.',
    'features.card1.title': 'Media & Inventory Management',
    'features.card1.subtitle': 'Turn screens into sellable media products',
    'features.card1.desc1': 'Venues can create media pages (Venue / Space / Screen)',
    'features.card1.desc2': 'Clearly set slot specs, dimensions, playback times',
    'features.card1.desc3': 'Support multi-screen, multi-venue centralized management',
    'features.card1.desc4': 'Instant listing, adjust anytime, no manual quoting',
    'features.card1.target': 'Suitable for: Exhibition halls, malls, event venues, transport hubs',
    'features.card2.title': 'Ad Inventory Marketplace',
    'features.card2.subtitle': 'Shop for ad slots like shopping for products',
    'features.card2.desc1': 'Advertisers can browse all available slots directly',
    'features.card2.desc2': 'Quickly filter by venue, time, price',
    'features.card2.desc3': 'Transparent info for every slot, no back-and-forth inquiry',
    'features.card2.desc4': 'No agency, no broker, direct matching',
    'features.card2.highlight': '👉 De-intermediation, fully transparent price & resources',
    'features.card3.title': 'Instant Order & Scheduled Playback',
    'features.card3.subtitle': 'Order placed, system plays automatically',
    'features.card3.desc1': 'Online ordering, no manual confirmation',
    'features.card3.desc2': 'System automatically handles scheduling and playback settings',
    'features.card3.desc3': 'Support specific dates, times, rotation rules',
    'features.card3.desc4': 'Ad content can be updated/replaced instantly',
    'features.card3.highlight': 'Truly: Order ≠ Waiting, but Instant Effect',
    'features.card4.title': 'Playback Monitoring & Status Feedback',
    'features.card4.subtitle': 'See the status of every ad',
    'features.card4.desc1': 'Real-time display of Playing / Completed / Scheduled',
    'features.card4.desc2': 'Venue and screen status at a glance',
    'features.card4.desc3': 'Reduce communication costs, avoid manual reconciliation',
    'features.card5.title': 'Data & Performance Tracking (Building)',
    'features.card5.subtitle': 'Make ads not just played, but seen',
    'features.card5.desc1': 'Complete playback records retained',
    'features.card5.desc2': 'Can integrate foot traffic / ticketing data (by plan)',
    'features.card5.desc3': 'Basis for future optimization and pricing',
    'features.card6.title': 'Permission & Role Management',
    'features.card6.subtitle': 'Venues and Advertisers focus on their own tasks',
    'features.card6.desc1': 'Venues: Manage media, slots, and revenue',
    'features.card6.desc2': 'Advertisers: Select slots, order, upload, view performance',
    'features.card6.desc3': 'Clear permission separation, smooth workflow',
    'features.reason1': 'Ad delivery process fully online',
    'features.reason2': 'Price, inventory, playback fully transparent',
    'features.reason3': 'De-intermediated, less communication, less manpower',
    'features.reason4': 'Evolving from "Playback Tool" to "Trading Platform"',
    'features.why.title': 'Why Choose AZIO1AD?',
    'features.why.description': 'AZIO1AD is a system that allows direct ad ordering and instant playback.',
    'features.cta.title': 'Ready to experience the new ad delivery model?',
    'features.cta.description': 'Whether you are a venue owner or an advertiser, AZIO1AD can create new value for you.',
    'features.cta.button.trial': 'Start Free Trial',
    'features.cta.button.demo': 'Book Demo',

    // Case Studies
    'case.hero.title': 'Success Stories',
    'case.hero.subtitle': 'See how other businesses create value with AZIO1AD.',
    'case.nangang.title': 'Nangang Exhibition Center',
    'case.nangang.desc': 'By adopting AZIO1AD digital signage management system, they transformed idle screens in the hall into high-value ad inventory, successfully increasing non-exhibition period revenue by 30%.',
    'case.retail.title': 'Chain Retail Stores',
    'case.retail.desc': 'Using AZIO1AD network function to unify management of promotional content across 50 stores in Taiwan, and opening remaining slots for external brands, creating extra revenue.',
    'caseStudies.hero.title': 'Case Studies',
    'caseStudies.hero.description': 'See how leading venue owners create value with AZIO1AD',
    'caseStudies.nangang.location': 'Taipei Nangang Exhibition Center',
    'caseStudies.nangang.badge': 'Largest Exhibition Venue in Taiwan, Digital Transformation Model',
    'caseStudies.nangang.solution': 'Exhibition Venue Solution',
    'caseStudies.nangang.title': 'Nangang Exhibition Center: Building a Fully Transparent Digital Ad Marketplace',
    'caseStudies.nangang.description': 'Nangang Exhibition Center uses AZIO1AD to manage multiple ad screens simultaneously and sell ads in the simplest way. Nearby restaurants, exhibitors, and non-exhibiting vendors can register an account to purchase ad slots online, checking availability anytime with transparent pricing for easy budget management.',
    'caseStudies.nangang.feature1.title': 'Centralized Multi-screen Management',
    'caseStudies.nangang.feature1.desc': 'Unified backend to manage all digital signage, instant content updates',
    'caseStudies.nangang.feature2.title': 'Maximize Ad Revenue',
    'caseStudies.nangang.feature2.desc': 'Idle slots automatically turn into sellable inventory, creating extra revenue',
    'caseStudies.nangang.feature3.title': 'Self-service Ad Delivery',
    'caseStudies.nangang.feature3.desc': 'Advertisers select, order, and upload by themselves, significantly reducing labor costs',
    'caseStudies.nangang.cta': 'Learn More Venue Solutions',
    'caseStudies.cta.title': 'Want to create extra revenue for your venue?',
    'caseStudies.cta.description': 'Join the AZIO1AD ecosystem and turn idle screens into profitable digital assets.',
    'caseStudies.cta.button.mediaOwner': 'I am a Venue Owner',
    'caseStudies.cta.button.advertiser': 'I am an Advertiser',

    // Get Started
    'getstarted.title': 'Choose Your Role',
    'getstarted.subtitle': 'Whether you want to buy ads or sell inventory, we have you covered.',
    'getstarted.advertiser.title': 'I am an Advertiser',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': 'I want to buy ad slots to promote my brand or product.',
    'getstarted.advertiser.feature1': 'Browse premium inventory',
    'getstarted.advertiser.feature2': 'Transparent pricing, online booking',
    'getstarted.advertiser.feature3': 'Instant launch, performance tracking',
    'getstarted.advertiser.cta': 'I am an Advertiser',
    'getstarted.media.title': 'I am a Media Owner',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': 'I want to list ad screens to monetize traffic.',
    'getstarted.media.feature1': 'Easily manage multi-venue screens',
    'getstarted.media.feature2': 'Custom inventory and pricing',
    'getstarted.media.feature3': 'Automated scheduling and reports',
    'getstarted.media.cta': 'I am a Media Owner',
    'getStarted.title': 'Ready to Get Started?',
    'getStarted.subtitle': 'Choose your role and experience the digital ad revolution with AZIO1AD.',
    'getStarted.advertiser.title': 'I am an Advertiser',
    'getStarted.advertiser.desc': 'I want to buy ad slots to promote my brand or product.',
    'getStarted.advertiser.feature1': 'Browse premium inventory',
    'getStarted.advertiser.feature2': 'Transparent pricing, online booking',
    'getStarted.advertiser.feature3': 'Instant launch, performance tracking',
    'getStarted.advertiser.button': 'I am an Advertiser',
    'getStarted.mediaOwner.title': 'I am a Media Owner',
    'getStarted.mediaOwner.desc': 'I want to list ad screens to monetize traffic.',
    'getStarted.mediaOwner.feature1': 'Easily manage multi-venue screens',
    'getStarted.mediaOwner.feature2': 'Custom inventory and pricing',
    'getStarted.mediaOwner.feature3': 'Automated scheduling and reports',
    'getStarted.mediaOwner.button': 'I am a Media Owner',
  },
  ja: {
    // Navbar
    'nav.features': '機能',
    'nav.solutions': 'ソリューション',
    'nav.pricing': '料金プラン',
    'nav.caseStudies': '導入事例',
    'nav.about': '私たちについて',
    'nav.advertiser': '広告主の方',
    'nav.advertiser.desc': '広告を購入し、ターゲット層にリーチ',
    'nav.mediaOwner': 'メディアオーナーの方',
    'nav.mediaOwner.desc': '広告枠を販売し、収益化',
    'nav.freeTrial': '無料トライアル',

    // Footer
    'footer.product': '製品',
    'footer.company': '会社情報',
    'footer.legal': '法的情報',
    'footer.contact': 'お問い合わせ',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',

    // Home
    'home.hero.title': 'スマートメディア\n取引管理システム',
    'home.hero.subtitle': 'AZIO1ADは広告枠の売買方法を再定義します。すべてのスクリーンを収益可能なメディア資産に変え、完全に透明でリアルタイムな広告取引体験を提供します。',
    'home.hero.cta': '無料トライアルを開始',
    'home.hero.demo': 'デモを予約',
    'home.hero.badge': '台湾初の仲介なしDOOH SaaSプラットフォーム',
    'home.features.security': 'エンタープライズセキュリティ',
    'home.features.instant': '即時掲載・販売',
    'home.features.title': 'なぜAZIO1ADが選ばれるのか？',
    'home.features.subtitle': '従来の広告購入のブラックボックスを打破し、これまでにない透明性と効率性を提供します。',
    'home.features.transparency.title': '透明な価格設定',
    'home.features.transparency.desc': 'すべての広告枠価格は公開され透明です。広告主はオンラインで直接比較・注文でき、メディアオーナーは独自に価格を設定できます。',
    'home.features.efficiency.title': '即時掲載、迅速な収益化',
    'home.features.efficiency.desc': 'メディアオーナーはいつでも空きスクリーンを掲載できます。広告主は空き状況を確認し、即座にキャンペーンを開始できます。',
    'home.features.data.title': 'データ駆動型ターゲティング',
    'home.features.data.desc': '人流分析とチケットデータと統合し、広告主がターゲットオーディエンスを正確に特定し、コンバージョンを向上させるのを支援します。',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.subtitle': '今すぐAZIO1ADに参加して、新しい広告取引モデルを体験してください。',
    'home.cta.advertiser': '私は広告主です',
    'home.cta.mediaOwner': '私はメディアオーナーです',

    // Advertiser
    'advertiser.hero.title': '精密なターゲティング、\n真のオーディエンスにリーチ',    'advertiser.hero.subtitle': '無効な露出に別れを告げましょう。AZIO1ADは台湾全土のプレミアム会場と直接つながり、データ駆動型の予算で広告効果を最大化します。',
    'advertiser.hero.badge': '広告主向け',
    'advertiser.why.title': 'なぜAZIO1ADを選ぶのか？',
    'advertiser.why.description': '私たちは単なる広告枠ではなく、消費者との深いつながりの機会を提供します。',
    'advertiser.why.card1.title': '正確な会場ターゲティング',
    'advertiser.why.card1.desc': '会場タイプ（展示会、オフィス、小売）と人流特性に基づいて、ターゲットオーディエンスを正確に絞り込みます。',
    'advertiser.why.card2.title': '透明な価格設定',
    'advertiser.why.card2.desc': '広告枠の価格とスケジュールを直接確認でき、面倒な問い合わせプロセスを排除し、予算管理を正確に行えます。',
    'advertiser.why.card3.title': 'インタラクティブマーケティングモジュール',
    'advertiser.why.card3.desc': '抽選やアンケートなどのインタラクティブモジュールをサポートし、受動的な視聴を能動的なブランドインタラクションに変えます。',
    'advertiser.marketplace.badge.status': 'ステータス',
    'advertiser.marketplace.badge.active': 'アクティブ',
    'advertiser.marketplace.title.1': '広告在庫',
    'advertiser.marketplace.title.2': 'マーケットプレイス',
    'advertiser.marketplace.description': 'オンラインショッピングのように簡単に広告を購入できます。透明な価格と即時注文で、台湾全土のプレミアム在庫を閲覧できます。',
    'advertiser.marketplace.feature1.title': '透明な価格設定',
    'advertiser.marketplace.feature1.desc': 'すべての広告枠の価格は公開されており、隠れた料金はありません。',
    'advertiser.marketplace.feature2.title': 'リアルタイムの空き状況',
    'advertiser.marketplace.feature2.desc': '広告枠の空き状況をリアルタイムで確認し、すぐに予約できます。',
    'advertiser.marketplace.feature3.title': 'オンライン決済',
    'advertiser.marketplace.feature3.desc': '複数のオンライン決済方法をサポートし、迅速な取引を実現します。',
    'advertiser.interaction.title': 'チケットとインタラクションの統合',
    'advertiser.interaction.description': 'AZIO1チケットシステムと組み合わせて、広告をチケット購入プロセスや現場でのインタラクションに拡張し、より多くのタッチポイントを作成します。',
    'advertiser.interaction.list.1': 'チケットページ広告',
    'advertiser.interaction.list.2': '電子チケット広告',
    'advertiser.interaction.list.3': '現場抽選インタラクション',
    'advertiser.interaction.list.4': 'アンケート収集',
    'advertiser.interaction.cta': 'インタラクションプランの詳細',
    'advertiser.cta.button': '無料トライアルを開始',
    'advertiser.features.title': '露出だけでなく、深いインタラクションも',
    'advertiser.features.subtitle': '単なる広告枠ではなく、消費者との深いつながりの機会を提供します。',
    'advertiser.features.precise.title': '精密な場所ターゲティング',
    'advertiser.features.precise.desc': '場所のタイプ（展示会、オフィス、小売）と人流特性に基づいて、ターゲット顧客を正確に特定します。',
    'advertiser.features.transparent.title': '透明な価格設定',
    'advertiser.features.transparent.desc': '広告枠の価格とスケジュールを直接確認でき、面倒な問い合わせプロセスを省き、予算管理を改善します。',
    'advertiser.features.interactive.title': 'インタラクティブマーケティングモジュール',
    'advertiser.features.interactive.desc': '抽選やアンケートなどのインタラクティブモジュールをサポートし、受動的な視聴をブランドとの能動的な対話に変えます。',
    'advertiser.steps.title': '簡単な3ステップで開始',
    'advertiser.steps.1.title': '在庫を検索',
    'advertiser.steps.1.desc': '地域や場所のタイプで適切な広告枠をフィルタリングします。',
    'advertiser.steps.2.title': 'オンライン予約',
    'advertiser.steps.2.desc': 'スケジュールと価格を確認し、オンラインで直接予約・支払いを行います。',
    'advertiser.steps.3.title': 'クリエイティブをアップロード',
    'advertiser.steps.3.desc': '広告クリエイティブをアップロードします。システムが自動的に審査し、即座に公開します。',
    'advertiser.cta.title': '広告配信を始める準備はできましたか？',
    'advertiser.cta.description': '今すぐ登録して、台湾全土のプレミアム広告枠を閲覧しましょう。',
    'advertiser.cta.button.start': '無料トライアルを開始',
    'advertiser.cta.button.demo': 'デモを予約',

    // Media Owner
    'media.hero.title': '遊休スクリーンを、\n収益資産に変える',
    'media.hero.subtitle': '面倒な営業開拓は不要です。AZIO1ADは、場所のスクリーンを販売用に掲載し、広告主と自動的にマッチングさせ、簡単に追加収益を生み出すのを支援します。',
    'media.features.title': '場所の価値を最大化',
    'media.features.subtitle': 'スクリーンと広告注文を簡単に管理するための完全な管理ツールを提供します。',
    'media.features.management.title': 'クラウドスクリーン管理',
    'media.features.management.desc': 'クラウドダッシュボードを通じて、いつでもどこでも複数の場所のスクリーンコンテンツと再生スケジュールを管理できます。',
    'media.features.sales.title': '自動販売',
    'media.features.sales.desc': '広告枠の価格と販売可能な時間帯を設定します。システムは手動介入なしに広告主の注文を自動的にマッチングします。',
    'media.features.report.title': '収益レポート',
    'media.features.report.desc': '広告収益と再生データをリアルタイムで確認し、場所の運営状況を把握し、価格戦略を最適化します。',
    'media.steps.title': '簡単設定、即時収益化',
    'media.steps.1.title': '場所を登録',
    'media.steps.1.desc': '場所情報とスクリーン仕様を入力して、アカウント登録を完了します。',
    'media.steps.2.title': 'プレイヤーをインストール',
    'media.steps.2.desc': 'スクリーン機器にAZIO1ADプレイヤーをインストールします。',
    'media.steps.3.title': '収益化を開始',
    'media.steps.3.desc': '販売可能な時間帯と価格を設定し、広告主の注文を待って収益を得ます。',
    'mediaOwner.hero.badge': 'メディアオーナー向け',
    'mediaOwner.hero.title.1': '遊休スクリーンを、',
    'mediaOwner.hero.title.2': 'キャッシュフローに変える',
    'mediaOwner.hero.description': '展示会場、ショッピングモール、イベント会場など。AZIO1ADは、場所のスクリーンを収益可能なメディア資産に変え、簡単に管理し、自動的に利益を上げるのを支援します。',
    'mediaOwner.hero.cta': 'メディアパートナーになる',
    'mediaOwner.stats.title': '推定月間収益',
    'mediaOwner.stats.growth': '成長の可能性',
    'mediaOwner.stats.rent': '広告枠レンタル',
    'mediaOwner.stats.self': '自己プロモーション',
    'mediaOwner.why.title': 'なぜAZIO1ADメディアエコシステムに参加するのか？',
    'mediaOwner.why.description': 'デバイス管理と広告販売のすべての課題を解決するワンストップSaaSソリューションを提供します。',
    'mediaOwner.why.card1.title': '資産の収益化',
    'mediaOwner.why.card1.desc': '場所内のデジタルサイネージを公開市場に掲載し、広告主と直接つながり、追加の受動的収入を生み出します。',
    'mediaOwner.why.card2.title': '自動管理',
    'mediaOwner.why.card2.desc': 'すべてのスクリーンを統合クラウド管理。広告スケジュール、クリエイティブ審査、再生監視、すべて自動化。',
    'mediaOwner.why.card3.title': '仲介排除',
    'mediaOwner.why.card3.desc': '価格決定権と顧客リストを取り戻す。ブローカーへの高額な手数料はなくなり、収益を最大化します。',
    'mediaOwner.dashboard.badge': '強力なバックエンドシステム',
    'mediaOwner.dashboard.title.1': '一つのダッシュボード、',
    'mediaOwner.dashboard.title.2': 'すべてのスクリーンと収益を管理',
    'mediaOwner.dashboard.description': '場所の所有者向けに設計されたSaaS管理システム。1つのスクリーンでも100のスクリーンでも、コンテンツ配信と収益を簡単に管理できます。',
    'mediaOwner.dashboard.feature1': '複数場所の集中管理',
    'mediaOwner.dashboard.feature2': '即時コンテンツ挿入',
    'mediaOwner.dashboard.feature3': '収益分析レポート',
    'mediaOwner.dashboard.feature4': 'カスタム審査メカニズム',
    'mediaOwner.revenue.title.1': '多様な収益化モデル、',
    'mediaOwner.revenue.title.2': '第二の成長曲線を作成',
    'mediaOwner.revenue.description': '単純な広告枠レンタルを超えて、AZIO1ADはより多様な利益機会を提供します。チケットシステムとインタラクティブモジュールを組み合わせて、場所の価値を高めます。',
    'mediaOwner.revenue.item1.title': '枠レンタル収益',
    'mediaOwner.revenue.item1.desc': '価格と枠をカスタマイズし、広告主が購入できるように公開し、安定した賃料を得ます。',
    'mediaOwner.revenue.item2.title': 'インタラクティブモジュールアドオン',
    'mediaOwner.revenue.item2.desc': '抽選やゲームなどを提供し、広告主が追加購入できるようにして、単価を上げます。',
    'mediaOwner.revenue.item3.title': 'データレポート販売',
    'mediaOwner.revenue.item3.desc': '場所の人流とオーディエンス分析を高価値なデータレポートに変換します。',
    'mediaOwner.cta.title': 'あなたの場所はもっと価値がある',
    'mediaOwner.cta.description': 'AZIO1ADに参加して、今すぐ場所のデジタルトランスフォーメーションの旅を始めましょう。',
    'mediaOwner.cta.button.apply': 'メディアパートナーとして申請',
    'mediaOwner.cta.button.download': 'パートナーシップ資料をダウンロード',

    // Pricing
    'pricing.title': 'シンプルで透明な料金プラン',
    'pricing.subtitle': '始めたばかりの小さな場所でも、複数の拠点を持つ大企業でも、あなたに合ったプランがあります。',
    'pricing.advertiser.title': '広告主',
    'pricing.advertiser.desc': '登録無料、広告費のみ支払い',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ 月',
    'pricing.advertiser.feature1': 'プレミアム在庫を閲覧',
    'pricing.advertiser.feature2': '透明な価格設定',
    'pricing.advertiser.feature3': '即時公開と追跡',
    'pricing.advertiser.feature4': '基本データレポート',
    'pricing.media.starter.title': 'メディアオーナー - スターター',
    'pricing.media.starter.desc': '単一の場所または少数のスクリーン向け',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ 月',
    'pricing.media.starter.feature1': '1つの場所を管理',
    'pricing.media.starter.feature2': '最大3つのスクリーン',
    'pricing.media.starter.feature3': '基本スケジュール管理',
    'pricing.media.starter.feature4': '5% プラットフォーム手数料',
    'pricing.media.pro.title': 'メディアオーナー - プロ',
    'pricing.media.pro.desc': '複数の場所またはチェーン向け',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ 月 / スクリーン',
    'pricing.media.pro.feature1': '無制限の場所管理',
    'pricing.media.pro.feature2': '無制限のスクリーン数',
    'pricing.media.pro.feature3': '高度なスケジュールとインタラクション',
    'pricing.media.pro.feature4': '3% プラットフォーム手数料',
    'pricing.enterprise.title': 'エンタープライズ',
    'pricing.enterprise.desc': '大規模な場所または特別なニーズ向け',
    'pricing.enterprise.price': 'カスタム',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': '専用API連携',
    'pricing.enterprise.feature2': 'カスタム機能開発',
    'pricing.enterprise.feature3': '専用サポート',
    'pricing.enterprise.feature4': '割引プラットフォーム手数料',
    'pricing.cta': '今すぐ始める',
    'pricing.contact': 'お問い合わせ',
    'pricing.header.title.1': 'あなたに合ったプランを選んで、',
    'pricing.header.title.2': '収益化の旅を始めましょう',
    'pricing.header.description': '単一の店舗でも大規模な展示会場でも、AZIO1ADにはソリューションがあります。無料トライアルから完全なエコシステム統合まで、スクリーンの価値を最大化するのを支援します。',
    'pricing.plan.trial.name': 'トライアル',
    'pricing.plan.trial.desc': '個人的なテストや小規模な場所の体験向け',
    'pricing.plan.business.name': 'ビジネス',
    'pricing.plan.business.desc': '中小規模の場所向け、すぐに収益化を開始',
    'pricing.plan.flagship.name': 'フラッグシップ',
    'pricing.plan.flagship.desc': '大規模な場所やチェーン向け、完全なエコシステム統合',
    'pricing.period.month': '/ 月',
    'pricing.feature.1link': '1 再生リンク',
    'pricing.feature.basicSchedule': '基本クラウドスケジュール',
    'pricing.feature.sd': '標準画質出力',
    'pricing.feature.watermark': '透かし入り出力',
    'pricing.feature.adListing': '広告枠掲載権限',
    'pricing.feature.interaction': 'インタラクティブモジュール',
    'pricing.feature.api': 'API連携',
    'pricing.feature.5links': '5 再生リンク',
    'pricing.feature.advancedSchedule': '高度なクラウドスケジュール',
    'pricing.feature.hd': 'HD出力',
    'pricing.feature.noWatermark': '公式透かしなし',
    'pricing.feature.basicReport': '基本データレポート',
    'pricing.feature.unlimitedLinks': '無制限の再生リンク',
    'pricing.feature.multiLevel': '多層権限管理',
    'pricing.feature.4k': '4K超高画質出力',
    'pricing.feature.priority': '広告枠優先露出',
    'pricing.feature.apiFull': '完全なAPI連携 (チケット/POS)',
    'pricing.cta.start': '無料で開始',
    'pricing.cta.subscribe': '今すぐ購読',
    'pricing.cta.contact': 'お問い合わせ',
    'pricing.price.contact': '相談',
    'pricing.badge.popular': '一番人気',
    'pricing.faq.title': 'よくある質問',
    'pricing.faq.q1': '「再生リンク」とは何ですか？',
    'pricing.faq.a1': '再生リンクは、AZIO1ADシステムによって生成される固有のURLです。このURLを接続されたスクリーン（スマートTV、タブレット、デジタルサイネージなど）のブラウザに入力するだけで、設定した広告コンテンツの再生を開始できます。追加のハードウェアは必要ありません。',
    'pricing.faq.q2': 'トライアル版に有効期限はありますか？',
    'pricing.faq.a2': 'トライアル版には現在、厳密な有効期限はありません。システムの安定性と操作インターフェースを好きなだけテストできます。ただし、トライアル出力にはAZIO1ADの透かしが入り、広告収益化機能は使用できないことに注意してください。',
    'pricing.faq.q3': '広告マーケットプレイスから収益を得るにはどうすればよいですか？',
    'pricing.faq.a3': '「ビジネス」または「フラッグシップ」プランに登録した後、バックエンドでスクリーン在庫情報（場所、人流、サイズ）を設定できます。承認されると、在庫はAZIO1AD広告マーケットプレイスに掲載され、広告主が購入できるようになります。広告主が注文すると、収益分配を得ることができます。',
    'pricing.faq.q4': 'いつでもアップグレードまたはキャンセルできますか？',
    'pricing.faq.a4': 'はい、バックエンドでいつでもプランをアップグレードでき、新機能はすぐに有効になります。購読をキャンセルする場合、サービスは現在の請求サイクルの終了まで継続されます。',
    'pricing.cta.title': 'どのプランが適しているかわかりませんか？',
    'pricing.cta.description': '私たちの専門コンサルティングチームがいつでもお手伝いします。場所の規模とニーズをお知らせいただければ、最適な導入計画をご提案します。',
    'pricing.cta.button.consult': '相談を予約',
    'pricing.cta.button.learnMore': 'メディアオーナーのメリットをもっと知る',

    // About
    'about.hero.title': '私たちについて',
    'about.hero.subtitle': 'AZIO1ADは、技術革新を通じて、公平で透明かつ効率的な場所広告エコシステムを構築することに専念しています。',
    'about.mission.title': '私たちのミッション',
    'about.mission.desc': 'すべてのスクリーンを価値あるものにし、すべての広告がターゲットに正確に届くようにすること。私たちは、デジタルトランスフォーメーションとデータ活用が従来の広告市場の情報の非対称性を打破し、メディアオーナー、広告主、消費者の三方よしの状況を作り出せると信じています。',
    'about.vision.title': '私たちのビジョン',
    'about.vision.desc': '物理空間とデジタル広告をつなぎ、将来のDOOHの標準を定義する、アジアをリードする場所広告取引プラットフォームになること。',
    'about.team.title': '私たちのチーム',
    'about.team.desc': '私たちは、アドテク、ソフトウェア開発、ビジネスコンサルティングの専門家グループであり、豊富な業界経験と革新への情熱を持っています。',
    'about.hero.company': 'AZIO1 International Co., Ltd.',
    'about.hero.description': '私たちは、技術革新を通じてオンラインとオフラインのリソースを統合し、企業と消費者にシームレスなデジタル体験を提供することに専念しています。',
    'about.evolution.title': 'チケットから広告への進化',
    'about.evolution.subtitle': 'From Ticketing to Advertising',
    'about.evolution.p1': 'AZIO1 Internationalは<strong>AZIO1チケットシステム</strong>から始まり、大規模イベントや会場向けのチケットソリューションを深く掘り下げ、豊富な人流データと会場運営経験を蓄積しました。',
    'about.evolution.p2': 'サービス提供中、会場内の巨大な「アテンション資産」が十分に活用されていないことに気づきました。従来の看板にはデータサポートがなく、ターゲットオーディエンスに正確にリーチできませんでした。',
    'about.evolution.p3': 'そこで、チケットの人流データと広告配信を組み合わせ、<strong>AZIO1AD広告システム</strong>が誕生しました。これは単なる広告プラットフォームではなく、人流、データ、会場を統合したスマートエコシステムです。',
    'about.pillars.title': '3つのビジネスエコシステム',
    'about.pillars.description': 'AZIO1はデータを核として、チケット、広告、Eコマースをつなぎ、包括的なビジネスループを作成します。',
    'about.pillars.card1.subtitle': 'チケットシステム',
    'about.pillars.card1.desc': '購入、検証、入場管理のワンストップサービスを提供するプロフェッショナルなチケットソリューション。核心的な人流データを把握します。',
    'about.pillars.card2.subtitle': '広告システム',
    'about.pillars.card2.desc': '統合された会場広告配信および管理SaaS。人流を広告価値に変え、精密なマーケティングを実現します。',
    'about.pillars.card3.subtitle': 'Eコマースシステム',
    'about.pillars.card3.desc': 'Bサイドクライアントのオンライン商用化を支援し、システムツールとコンサルティングサービスを提供して、自社ブランドの販売チャネルを構築します。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.card1.title': '革新',
    'about.values.card1.desc': '技術の境界を絶えず打ち破り、従来のビジネスモデルを再定義します。',
    'about.values.card2.title': '統合',
    'about.values.card2.desc': 'オンラインデータとオフライン会場をつなぎ、シームレスな体験を生み出します。',
    'about.values.card3.title': '共存共栄',
    'about.values.card3.desc': '会場オーナー、広告主、消費者の三方よしの価値を創造します。',
    'about.cta.title': 'エコシステムに参加する準備はできましたか？',
    'about.cta.description': '会場オーナーでも広告主でも、AZIO1ADはあなたに新しい価値を創造できます。',
    'about.cta.button.mediaOwner': '私は会場オーナーです',
    'about.cta.button.advertiser': '私は広告主です',

    // Features
    'features.hero.title': '強力な機能、\nすべてのニーズを満たす',
    'features.hero.subtitle': '広告の公開からスクリーン管理まで、AZIO1ADは包括的なソリューションを提供します。',
    'features.list.title': 'コア機能一覧',
    'features.ad.management': '広告スケジュール管理',
    'features.ad.management.desc': '直感的なカレンダーインターフェースで、各スクリーンの広告スケジュールとコンテンツを簡単に管理できます。',
    'features.device.monitoring': 'デバイス状態監視',
    'features.device.monitoring.desc': 'スクリーンの接続状態と再生をリアルタイムで監視し、異常があれば自動的に通知します。',
    'features.data.analytics': 'データ分析レポート',
    'features.data.analytics.desc': '詳細な再生記録、人流データ、収益分析を提供し、意思決定の最適化を支援します。',
    'features.interactive': 'インタラクティブマーケティング',
    'features.interactive.desc': '抽選、投票、アンケートなどのインタラクティブ機能を内蔵し、広告への関与を高めます。',
    'features.card1.title': 'メディアと在庫の管理',
    'features.card1.subtitle': 'スクリーンを販売可能なメディア商品に変える',
    'features.card1.desc1': '会場はメディアページ（会場/スペース/スクリーン）を作成可能',
    'features.card1.desc2': '枠の仕様、寸法、再生時間を明確に設定',
    'features.card1.desc3': 'マルチスクリーン、マルチ会場の集中管理をサポート',
    'features.card1.desc4': '即時掲載、いつでも調整可能、手動見積もり不要',
    'features.card1.target': '対象：展示会場、モール、イベント会場、交通ハブ',
    'features.card2.title': '広告在庫マーケットプレイス',
    'features.card2.subtitle': '商品を買うように広告枠を選ぶ',
    'features.card2.desc1': '広告主は利用可能なすべての枠を直接閲覧可能',
    'features.card2.desc2': '会場、時間、価格ですばやくフィルタリング',
    'features.card2.desc3': 'すべての枠の情報が透明で、問い合わせのやり取りは不要',
    'features.card2.desc4': '代理店なし、ブローカーなし、直接マッチング',
    'features.card2.highlight': '👉 仲介排除、完全に透明な価格とリソース',
    'features.card3.title': '即時注文とスケジュール再生',
    'features.card3.subtitle': '注文完了、システムが自動再生',
    'features.card3.desc1': 'オンライン注文、手動確認不要',
    'features.card3.desc2': 'システムがスケジュールと再生設定を自動処理',
    'features.card3.desc3': '特定の日付、時間、ローテーションルールをサポート',
    'features.card3.desc4': '広告コンテンツは即座に更新/置換可能',
    'features.card3.highlight': '真実：注文 ≠ 待機、即時効果',
    'features.card4.title': '再生監視とステータスフィードバック',
    'features.card4.subtitle': 'すべての広告のステータスを確認',
    'features.card4.desc1': '再生中 / 完了 / スケジュール済みのリアルタイム表示',
    'features.card4.desc2': '会場とスクリーンの状態が一目瞭然',
    'features.card4.desc3': 'コミュニケーションコストを削減し、手動照合を回避',
    'features.card5.title': 'データとパフォーマンス追跡（構築中）',
    'features.card5.subtitle': '広告をただ流すだけでなく、見られるものにする',
    'features.card5.desc1': '完全な再生記録を保持',
    'features.card5.desc2': '人流 / チケットデータを統合可能（プランによる）',
    'features.card5.desc3': '将来の最適化と価格設定の基礎',
    'features.card6.title': '権限と役割の管理',
    'features.card6.subtitle': '会場と広告主はそれぞれのタスクに集中',
    'features.card6.desc1': '会場：メディア、枠、収益を管理',
    'features.card6.desc2': '広告主：枠の選択、注文、アップロード、パフォーマンス確認',
    'features.card6.desc3': '明確な権限分離、スムーズなワークフロー',
    'features.reason1': '広告配信プロセスが完全にオンライン化',
    'features.reason2': '価格、在庫、再生が完全に透明',
    'features.reason3': '仲介なし、コミュニケーション削減、省力化',
    'features.reason4': '「再生ツール」から「取引プラットフォーム」への進化',
    'features.why.title': 'なぜAZIO1ADを選ぶのか？',
    'features.why.description': 'AZIO1ADは、直接広告注文と即時再生を可能にするシステムです。',
    'features.cta.title': '新しい広告配信モデルを体験する準備はできましたか？',
    'features.cta.description': '会場オーナーでも広告主でも、AZIO1ADはあなたに新しい価値を創造できます。',
    'features.cta.button.trial': '無料トライアルを開始',
    'features.cta.button.demo': 'デモを予約',

    // Case Studies
    'case.hero.title': '成功事例',
    'case.hero.subtitle': '他の企業がAZIO1ADでどのように価値を創造しているかをご覧ください。',
    'case.nangang.title': '南港展覧館',
    'case.nangang.desc': 'AZIO1ADデジタルサイネージ管理システムを導入することで、館内の遊休スクリーンを高価値な広告枠に変え、非展示期間の収益を30%増加させることに成功しました。',
    'case.retail.title': 'チェーン小売店',
    'case.retail.desc': 'AZIO1ADネットワーク機能を利用して、台湾全土の50店舗のプロモーションコンテンツを一元管理し、残りの枠を外部ブランドに開放して追加収益を生み出しました。',
    'caseStudies.hero.title': '導入事例',
    'caseStudies.hero.description': '主要な会場オーナーがAZIO1ADでどのように価値を創造しているかをご覧ください',
    'caseStudies.nangang.location': '台北南港展覧館',
    'caseStudies.nangang.badge': '台湾最大の展示会場、デジタルトランスフォーメーションのモデル',
    'caseStudies.nangang.solution': '展示会場ソリューション',
    'caseStudies.nangang.title': '南港展覧館：完全に透明なデジタル広告マーケットプレイスの構築',
    'caseStudies.nangang.description': '南港展覧館はAZIO1ADを使用して、複数の広告スクリーンを同時に管理し、最も簡単な方法で広告を販売しています。近隣のレストラン、出展者、出展していないベンダーも、アカウントを登録するだけでオンラインで広告枠を購入でき、いつでも空き状況を確認でき、透明な価格設定でマーケティング予算管理が容易になります。',
    'caseStudies.nangang.feature1.title': 'マルチスクリーン集中管理',
    'caseStudies.nangang.feature1.desc': 'すべてのデジタルサイネージを管理する統一バックエンド、即時コンテンツ更新',
    'caseStudies.nangang.feature2.title': '広告収益の最大化',
    'caseStudies.nangang.feature2.desc': 'アイドル枠が自動的に販売可能な在庫に変わり、追加収益を生み出します',
    'caseStudies.nangang.feature3.title': 'セルフサービス広告配信',
    'caseStudies.nangang.feature3.desc': '広告主が自分で選択、注文、アップロードするため、人件費を大幅に削減できます',
    'caseStudies.nangang.cta': '会場ソリューションの詳細',
    'caseStudies.cta.title': 'あなたの会場でも追加収益を生み出したいですか？',
    'caseStudies.cta.description': 'AZIO1ADエコシステムに参加して、遊休スクリーンを収益性の高いデジタル資産に変えましょう。',
    'caseStudies.cta.button.mediaOwner': '私は会場オーナーです',
    'caseStudies.cta.button.advertiser': '私は広告主です',

    // Get Started
    'getstarted.title': '役割を選択',
    'getstarted.subtitle': '広告を購入したい場合でも、在庫を販売したい場合でも、対応可能です。',
    'getstarted.advertiser.title': '私は広告主です',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': 'ブランドや商品を宣伝するために広告枠を購入したい。',
    'getstarted.advertiser.feature1': 'プレミアム在庫を閲覧',
    'getstarted.advertiser.feature2': '透明な価格設定、オンライン注文',
    'getstarted.advertiser.feature3': '即時公開、成果追跡',
    'getstarted.advertiser.cta': '私は広告主です',
    'getstarted.media.title': '私はメディアオーナーです',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': 'トラフィックを収益化するために広告スクリーンを掲載したい。',
    'getstarted.media.feature1': '複数場所のスクリーンを簡単管理',
    'getstarted.media.feature2': 'カスタム枠と販売価格',
    'getstarted.media.feature3': '自動スケジュールと収益レポート',
    'getstarted.media.cta': '私はメディアオーナーです',
    'getStarted.title': '始める準備はできましたか？',
    'getStarted.subtitle': '役割を選択して、AZIO1ADでデジタル広告革命を体験してください。',
    'getStarted.advertiser.title': '私は広告主です',
    'getStarted.advertiser.desc': 'ブランドや商品を宣伝するために広告枠を購入したい。',
    'getStarted.advertiser.feature1': 'プレミアム在庫を閲覧',
    'getStarted.advertiser.feature2': '透明な価格設定、オンライン注文',
    'getStarted.advertiser.feature3': '即時公開、成果追跡',
    'getStarted.advertiser.button': '私は広告主です',
    'getStarted.mediaOwner.title': '私はメディアオーナーです',
    'getStarted.mediaOwner.desc': 'トラフィックを収益化するために広告スクリーンを掲載したい。',
    'getStarted.mediaOwner.feature1': '複数場所のスクリーンを簡単管理',
    'getStarted.mediaOwner.feature2': 'カスタム枠と販売価格',
    'getStarted.mediaOwner.feature3': '自動スケジュールと収益レポート',
    'getStarted.mediaOwner.button': '私はメディアオーナーです',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
