import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.features': '產品功能',
    'nav.solutions': '解決方案',
    'nav.pricing': '定價方案',
    'nav.caseStudies': '客戶案例',
    'nav.about': '關於我們',
    'nav.advertiser': '我是廣告主',
    'nav.advertiser.desc': '買廣告，精準投放目標場域',
    'nav.mediaOwner': '我是媒體方',
    'nav.mediaOwner.desc': '賣版位，閒置螢幕變現',
    'nav.freeTrial': '免費試用',

    // Footer
    'footer.product': '產品',
    'footer.company': '公司',
    'footer.legal': '法律',
    'footer.contact': '聯絡我們',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': '隱私權政策',
    'footer.terms': '服務條款',

    // Home
    'home.hero.title': '智映媒體\n交易管理系統',
    'home.hero.subtitle': 'AZIO1AD 重新定義廣告版位的銷售與購買方式。讓每個螢幕都成為可變現的媒體資產，打造全透明、即時化的廣告交易體驗。',
    'home.hero.cta': '開始免費試用',
    'home.hero.demo': '預約專人演示',
    'home.hero.badge': '台灣首個去經銷化場域廣告 SaaS 平台',
    'home.features.security': '企業級資安防護',
    'home.features.instant': '即時上架銷售',
    'home.features.title': '為什麼選擇 AZIO1AD？',
    'home.features.subtitle': '我們打破傳統廣告採購的黑箱作業，為您帶來前所未有的透明與效率。',
    'home.features.transparency.title': '價格透明，拒絕黑箱',
    'home.features.transparency.desc': '所有版位價格公開透明，廣告主可直接線上比價下單，媒體方可自主定價，告別層層剝削。',
    'home.features.efficiency.title': '即時上架，快速變現',
    'home.features.efficiency.desc': '媒體方可隨時上架閒置螢幕，廣告主可即時查詢檔期並投放，大幅縮短交易流程。',
    'home.features.data.title': '數據驅動，精準投放',
    'home.features.data.desc': '整合人流分析與票務數據，協助廣告主精準鎖定目標受眾，提升廣告轉換成效。',
    'home.cta.title': '準備好開始了嗎？',
    'home.cta.subtitle': '立即加入 AZIO1AD，體驗全新的廣告交易模式。',
    'home.cta.advertiser': '我是廣告主',
    'home.cta.mediaOwner': '我是媒體方',

    // Advertiser
    'advertiser.hero.title': '精準投放，\n觸及真實受眾',
    'advertiser.hero.subtitle': '告別無效曝光。AZIO1AD 讓您直接對接全台優質場域，用數據驅動每一分預算，極大化廣告效益。',
    'advertiser.features.title': '不只是曝光，還能深度互動',
    'advertiser.features.subtitle': '我們提供的不僅是廣告版位，更是與消費者深度連結的機會。',
    'advertiser.features.precise.title': '精準場域鎖定',
    'advertiser.features.precise.desc': '依據場域類型（展覽、商辦、零售）與人流特徵，精準鎖定您的目標客群。',
    'advertiser.features.transparent.title': '價格公開透明',
    'advertiser.features.transparent.desc': '直接查看版位價格與檔期，免去繁瑣詢價過程，預算控管更精準。',
    'advertiser.features.interactive.title': '互動行銷模組',
    'advertiser.features.interactive.desc': '支援抽獎、問卷等互動模組，將被動觀看轉化為與品牌的主動互動。',
    'advertiser.steps.title': '簡單三步驟，開始投放',
    'advertiser.steps.1.title': '搜尋版位',
    'advertiser.steps.1.desc': '依據地區、場域類型篩選適合的廣告版位。',
    'advertiser.steps.2.title': '線上預訂',
    'advertiser.steps.2.desc': '確認檔期與價格，直接線上完成預訂與付款。',
    'advertiser.steps.3.title': '上傳素材',
    'advertiser.steps.3.desc': '上傳廣告素材，系統自動審核後即刻上線。',

    // Media Owner
    'media.hero.title': '閒置螢幕，\n變身獲利資產',
    'media.hero.subtitle': '無需繁瑣業務開發。AZIO1AD 協助您將場域螢幕上架銷售，自動媒合廣告主，輕鬆創造額外營收。',
    'media.features.title': '讓您的場域發揮最大價值',
    'media.features.subtitle': '我們提供完整的管理工具，讓您輕鬆管理螢幕與廣告訂單。',
    'media.features.management.title': '雲端螢幕管理',
    'media.features.management.desc': '透過雲端後台，隨時隨地管理多個場域的螢幕內容與播放排程。',
    'media.features.sales.title': '自動化銷售',
    'media.features.sales.desc': '設定版位價格與可售時段，系統自動媒合廣告主訂單，無需人工介入。',
    'media.features.report.title': '收益報表分析',
    'media.features.report.desc': '即時查看廣告收益與播放數據，掌握場域營運狀況，優化定價策略。',
    'media.steps.title': '輕鬆啟用，立即變現',
    'media.steps.1.title': '註冊場域',
    'media.steps.1.desc': '填寫場域資訊與螢幕規格，完成帳號註冊。',
    'media.steps.2.title': '安裝播放器',
    'media.steps.2.desc': '將 AZIO1AD 播放器安裝至您的螢幕設備。',
    'media.steps.3.title': '開始獲利',
    'media.steps.3.desc': '設定可售時段與價格，等待廣告主下單獲取收益。',

    // Pricing
    'pricing.title': '簡單透明的定價方案',
    'pricing.subtitle': '無論您是剛起步的小型場域，還是擁有多個據點的大型企業，我們都有適合您的方案。',
    'pricing.advertiser.title': '廣告主',
    'pricing.advertiser.desc': '免費註冊，僅需支付廣告費用',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ 月',
    'pricing.advertiser.feature1': '瀏覽全台優質版位',
    'pricing.advertiser.feature2': '價格透明，線上比價',
    'pricing.advertiser.feature3': '即時投放，成效追蹤',
    'pricing.advertiser.feature4': '基本數據報表',
    'pricing.media.starter.title': '媒體方 - 體驗版',
    'pricing.media.starter.desc': '適合單一場域或少量螢幕',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ 月',
    'pricing.media.starter.feature1': '管理 1 個場域',
    'pricing.media.starter.feature2': '最多 3 個螢幕',
    'pricing.media.starter.feature3': '基本排程管理',
    'pricing.media.starter.feature4': '5% 平台服務費',
    'pricing.media.pro.title': '媒體方 - 專業版',
    'pricing.media.pro.desc': '適合多場域或連鎖企業',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ 月 / 螢幕',
    'pricing.media.pro.feature1': '無限場域管理',
    'pricing.media.pro.feature2': '無限螢幕數量',
    'pricing.media.pro.feature3': '進階排程與互動模組',
    'pricing.media.pro.feature4': '3% 平台服務費',
    'pricing.enterprise.title': '企業客製方案',
    'pricing.enterprise.desc': '針對大型場域或特殊需求',
    'pricing.enterprise.price': '專案報價',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': '專屬 API 串接',
    'pricing.enterprise.feature2': '客製化功能開發',
    'pricing.enterprise.feature3': '專人技術支援',
    'pricing.enterprise.feature4': '優惠平台服務費',
    'pricing.cta': '立即開始',
    'pricing.contact': '聯絡我們',

    // About
    'about.hero.title': '關於我們',
    'about.hero.subtitle': 'AZIO1AD 致力於透過科技創新，打造公平、透明、高效的場域廣告生態系。',
    'about.mission.title': '我們的使命',
    'about.mission.desc': '讓每一個螢幕都能發揮價值，讓每一次投放都能精準觸達。我們相信，透過數位轉型與數據賦能，可以打破傳統廣告市場的資訊不對稱，創造媒體方、廣告主與消費者的三贏局面。',
    'about.vision.title': '我們的願景',
    'about.vision.desc': '成為亞洲領先的場域廣告交易平台，連結實體空間與數位廣告，定義未來的家外媒體（DOOH）標準。',
    'about.team.title': '我們的團隊',
    'about.team.desc': '我們是一群來自廣告科技、軟體開發與商業顧問領域的專業人才，擁有豐富的產業經驗與創新熱情。',

    // Features
    'features.hero.title': '強大功能，\n滿足您的所有需求',
    'features.hero.subtitle': '從廣告投放到螢幕管理，AZIO1AD 提供全方位的解決方案。',
    'features.list.title': '核心功能一覽',
    'features.ad.management': '廣告檔期管理',
    'features.ad.management.desc': '直覺的行事曆介面，輕鬆管理各個螢幕的廣告檔期與播放內容。',
    'features.device.monitoring': '設備狀態監控',
    'features.device.monitoring.desc': '即時監控螢幕連線狀態與播放畫面，異常狀況自動通報。',
    'features.data.analytics': '數據分析報表',
    'features.data.analytics.desc': '提供詳細的播放紀錄、人流數據與收益分析，協助決策優化。',
    'features.interactive': '互動行銷模組',
    'features.interactive.desc': '內建抽獎、投票、問卷等互動功能，提升廣告參與度。',

    // Case Studies
    'case.hero.title': '客戶成功案例',
    'case.hero.subtitle': '看看其他企業如何透過 AZIO1AD 創造價值。',
    'case.nangang.title': '南港展覽館',
    'case.nangang.desc': '透過 AZIO1AD 導入數位看板管理系統，將展館內的閒置螢幕轉化為高價值的廣告版位，成功提升 30% 的非展期營收。',
    'case.retail.title': '連鎖零售通路',
    'case.retail.desc': '利用 AZIO1AD 的聯播網功能，統一管理全台 50 間門市的促銷內容，並將剩餘時段開放外部品牌投放，創造額外收益。',

    // Get Started
    'getstarted.title': '選擇您的身份',
    'getstarted.subtitle': '無論您是想購買廣告還是銷售版位，我們都能滿足您的需求。',
    'getstarted.advertiser.title': '我是廣告主',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': '我想購買廣告版位，推廣我的品牌或商品。',
    'getstarted.advertiser.feature1': '瀏覽全台優質版位',
    'getstarted.advertiser.feature2': '價格透明，線上下單',
    'getstarted.advertiser.feature3': '即刻投放，成效追蹤',
    'getstarted.advertiser.cta': '我是廣告主',
    'getstarted.media.title': '我是媒體方',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': '我想上架廣告螢幕，將流量變現創造收益。',
    'getstarted.media.feature1': '輕鬆管理多場域螢幕',
    'getstarted.media.feature2': '自訂版位與銷售價格',
    'getstarted.media.feature3': '自動化排程與收益報表',
    'getstarted.media.cta': '我是媒體方',
  },
  en: {
    // Navbar
    'nav.features': 'Features',
    'nav.solutions': 'Solutions',
    'nav.pricing': 'Pricing',
    'nav.caseStudies': 'Case Studies',
    'nav.about': 'About Us',
    'nav.advertiser': 'Advertiser',
    'nav.advertiser.desc': 'Buy ads, target precise venues',
    'nav.mediaOwner': 'Media Owner',
    'nav.mediaOwner.desc': 'Sell inventory, monetize screens',
    'nav.freeTrial': 'Free Trial',

    // Footer
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact Us',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Home
    'home.hero.title': 'Smart Media\nTrading System',
    'home.hero.subtitle': 'AZIO1AD redefines how ad inventory is sold and bought. Turn every screen into a monetizable media asset with a fully transparent, real-time trading experience.',
    'home.hero.cta': 'Start Free Trial',
    'home.hero.demo': 'Book Demo',
    'home.hero.badge': 'Taiwan\'s First De-intermediated DOOH SaaS Platform',
    'home.features.security': 'Enterprise Security',
    'home.features.instant': 'Instant Listing',
    'home.features.title': 'Why Choose AZIO1AD?',
    'home.features.subtitle': 'We break the black box of traditional ad buying, bringing you unprecedented transparency and efficiency.',
    'home.features.transparency.title': 'Transparent Pricing',
    'home.features.transparency.desc': 'All inventory prices are open and transparent. Advertisers can compare and book online directly. Media owners set their own prices.',
    'home.features.efficiency.title': 'Instant Listing, Fast Monetization',
    'home.features.efficiency.desc': 'Media owners can list idle screens anytime. Advertisers can check availability and launch campaigns instantly.',
    'home.features.data.title': 'Data-Driven Targeting',
    'home.features.data.desc': 'Integrated with foot traffic analysis and ticketing data to help advertisers precisely target audiences and improve conversion.',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.subtitle': 'Join AZIO1AD now and experience the new model of ad trading.',
    'home.cta.advertiser': 'I am an Advertiser',
    'home.cta.mediaOwner': 'I am a Media Owner',

    // Advertiser
    'advertiser.hero.title': 'Precise Targeting,\nReach Real Audiences',
    'advertiser.hero.subtitle': 'Say goodbye to ineffective exposure. AZIO1AD connects you directly with premium venues across Taiwan, maximizing ad effectiveness with data-driven budgets.',
    'advertiser.features.title': 'More Than Exposure, Deep Interaction',
    'advertiser.features.subtitle': 'We provide not just ad slots, but opportunities for deep connection with consumers.',
    'advertiser.features.precise.title': 'Precise Venue Targeting',
    'advertiser.features.precise.desc': 'Target your audience precisely based on venue type (exhibition, office, retail) and foot traffic characteristics.',
    'advertiser.features.transparent.title': 'Transparent Pricing',
    'advertiser.features.transparent.desc': 'View inventory prices and schedules directly, eliminating tedious inquiry processes for better budget control.',
    'advertiser.features.interactive.title': 'Interactive Marketing Modules',
    'advertiser.features.interactive.desc': 'Support interactive modules like lucky draws and surveys, turning passive viewing into active brand engagement.',
    'advertiser.steps.title': 'Start in 3 Simple Steps',
    'advertiser.steps.1.title': 'Search Inventory',
    'advertiser.steps.1.desc': 'Filter suitable ad slots by region and venue type.',
    'advertiser.steps.2.title': 'Book Online',
    'advertiser.steps.2.desc': 'Confirm schedule and price, then book and pay directly online.',
    'advertiser.steps.3.title': 'Upload Creative',
    'advertiser.steps.3.desc': 'Upload ad creatives. System automatically reviews and launches them instantly.',

    // Media Owner
    'media.hero.title': 'Idle Screens,\nProfitable Assets',
    'media.hero.subtitle': 'No need for tedious business development. AZIO1AD helps you list venue screens for sale, automatically matching advertisers to create extra revenue easily.',
    'media.features.title': 'Maximize Your Venue Value',
    'media.features.subtitle': 'We provide complete management tools for you to easily manage screens and ad orders.',
    'media.features.management.title': 'Cloud Screen Management',
    'media.features.management.desc': 'Manage screen content and playlists across multiple venues anytime, anywhere via cloud dashboard.',
    'media.features.sales.title': 'Automated Sales',
    'media.features.sales.desc': 'Set inventory prices and available slots. System automatically matches advertiser orders without manual intervention.',
    'media.features.report.title': 'Revenue Reports',
    'media.features.report.desc': 'View ad revenue and playback data in real-time to master venue operations and optimize pricing strategies.',
    'media.steps.title': 'Easy Setup, Instant Monetization',
    'media.steps.1.title': 'Register Venue',
    'media.steps.1.desc': 'Fill in venue info and screen specs to complete account registration.',
    'media.steps.2.title': 'Install Player',
    'media.steps.2.desc': 'Install AZIO1AD player on your screen equipment.',
    'media.steps.3.title': 'Start Earning',
    'media.steps.3.desc': 'Set available slots and prices, wait for advertisers to book and earn revenue.',

    // Pricing
    'pricing.title': 'Simple & Transparent Pricing',
    'pricing.subtitle': 'Whether you are a small venue just starting out or a large enterprise with multiple locations, we have a plan for you.',
    'pricing.advertiser.title': 'Advertiser',
    'pricing.advertiser.desc': 'Free registration, pay only for ads',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ mo',
    'pricing.advertiser.feature1': 'Browse premium inventory',
    'pricing.advertiser.feature2': 'Transparent pricing',
    'pricing.advertiser.feature3': 'Instant launch & tracking',
    'pricing.advertiser.feature4': 'Basic data reports',
    'pricing.media.starter.title': 'Media Owner - Starter',
    'pricing.media.starter.desc': 'For single venue or few screens',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ mo',
    'pricing.media.starter.feature1': 'Manage 1 venue',
    'pricing.media.starter.feature2': 'Up to 3 screens',
    'pricing.media.starter.feature3': 'Basic schedule management',
    'pricing.media.starter.feature4': '5% platform fee',
    'pricing.media.pro.title': 'Media Owner - Pro',
    'pricing.media.pro.desc': 'For multi-venue or chains',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ mo / screen',
    'pricing.media.pro.feature1': 'Unlimited venues',
    'pricing.media.pro.feature2': 'Unlimited screens',
    'pricing.media.pro.feature3': 'Advanced scheduling & interaction',
    'pricing.media.pro.feature4': '3% platform fee',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.desc': 'For large venues or special needs',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': 'Dedicated API integration',
    'pricing.enterprise.feature2': 'Custom feature development',
    'pricing.enterprise.feature3': 'Dedicated support',
    'pricing.enterprise.feature4': 'Discounted platform fee',
    'pricing.cta': 'Get Started',
    'pricing.contact': 'Contact Us',

    // About
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'AZIO1AD is dedicated to building a fair, transparent, and efficient venue advertising ecosystem through technological innovation.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To make every screen valuable and every ad reach its target precisely. We believe digital transformation and data empowerment can break information asymmetry in the traditional ad market, creating a win-win-win for media owners, advertisers, and consumers.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To become Asia\'s leading venue advertising trading platform, connecting physical spaces with digital ads, defining the future standard of DOOH.',
    'about.team.title': 'Our Team',
    'about.team.desc': 'We are a group of professionals from ad tech, software development, and business consulting, with rich industry experience and passion for innovation.',

    // Features
    'features.hero.title': 'Powerful Features,\nMeet All Your Needs',
    'features.hero.subtitle': 'From ad launching to screen management, AZIO1AD provides comprehensive solutions.',
    'features.list.title': 'Core Features',
    'features.ad.management': 'Ad Schedule Management',
    'features.ad.management.desc': 'Intuitive calendar interface to easily manage ad schedules and content for each screen.',
    'features.device.monitoring': 'Device Status Monitoring',
    'features.device.monitoring.desc': 'Real-time monitoring of screen connection status and playback, with automatic alerts for abnormalities.',
    'features.data.analytics': 'Data Analytics Reports',
    'features.data.analytics.desc': 'Detailed playback records, foot traffic data, and revenue analysis to help optimize decisions.',
    'features.interactive': 'Interactive Marketing',
    'features.interactive.desc': 'Built-in lucky draws, voting, surveys, and other interactive functions to increase ad engagement.',

    // Case Studies
    'case.hero.title': 'Success Stories',
    'case.hero.subtitle': 'See how other businesses create value with AZIO1AD.',
    'case.nangang.title': 'Nangang Exhibition Center',
    'case.nangang.desc': 'By adopting AZIO1AD digital signage management system, they transformed idle screens in the hall into high-value ad inventory, successfully increasing non-exhibition period revenue by 30%.',
    'case.retail.title': 'Chain Retail Stores',
    'case.retail.desc': 'Using AZIO1AD network function to unify management of promotional content across 50 stores in Taiwan, and opening remaining slots for external brands, creating extra revenue.',

    // Get Started
    'getstarted.title': 'Choose Your Role',
    'getstarted.subtitle': 'Whether you want to buy ads or sell inventory, we have you covered.',
    'getstarted.advertiser.title': 'I am an Advertiser',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': 'I want to buy ad slots to promote my brand or product.',
    'getstarted.advertiser.feature1': 'Browse premium inventory',
    'getstarted.advertiser.feature2': 'Transparent pricing, online booking',
    'getstarted.advertiser.feature3': 'Instant launch, performance tracking',
    'getstarted.advertiser.cta': 'I am an Advertiser',
    'getstarted.media.title': 'I am a Media Owner',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': 'I want to list ad screens to monetize traffic.',
    'getstarted.media.feature1': 'Easily manage multi-venue screens',
    'getstarted.media.feature2': 'Custom inventory and pricing',
    'getstarted.media.feature3': 'Automated scheduling and reports',
    'getstarted.media.cta': 'I am a Media Owner',
  },
  ja: {
    // Navbar
    'nav.features': '機能',
    'nav.solutions': 'ソリューション',
    'nav.pricing': '料金プラン',
    'nav.caseStudies': '導入事例',
    'nav.about': '私たちについて',
    'nav.advertiser': '広告主の方',
    'nav.advertiser.desc': '広告を購入し、ターゲット層にリーチ',
    'nav.mediaOwner': 'メディアオーナーの方',
    'nav.mediaOwner.desc': '広告枠を販売し、収益化',
    'nav.freeTrial': '無料トライアル',

    // Footer
    'footer.product': '製品',
    'footer.company': '会社情報',
    'footer.legal': '法的情報',
    'footer.contact': 'お問い合わせ',
    'footer.rights': '© 2025 AZIO1AD. All rights reserved.',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',

    // Home
    'home.hero.title': 'スマートメディア\n取引管理システム',
    'home.hero.subtitle': 'AZIO1ADは広告枠の売買方法を再定義します。すべてのスクリーンを収益可能なメディア資産に変え、完全に透明でリアルタイムな広告取引体験を提供します。',
    'home.hero.cta': '無料トライアルを開始',
    'home.hero.demo': 'デモを予約',
    'home.hero.badge': '台湾初の仲介なしDOOH SaaSプラットフォーム',
    'home.features.security': 'エンタープライズセキュリティ',
    'home.features.instant': '即時掲載・販売',
    'home.features.title': 'なぜAZIO1ADが選ばれるのか？',
    'home.features.subtitle': '従来の広告購入のブラックボックスを打破し、これまでにない透明性と効率性を提供します。',
    'home.features.transparency.title': '透明な価格設定',
    'home.features.transparency.desc': 'すべての広告枠価格は公開され透明です。広告主はオンラインで直接比較・注文でき、メディアオーナーは独自に価格を設定できます。',
    'home.features.efficiency.title': '即時掲載、迅速な収益化',
    'home.features.efficiency.desc': 'メディアオーナーはいつでも空きスクリーンを掲載できます。広告主は空き状況を確認し、即座にキャンペーンを開始できます。',
    'home.features.data.title': 'データ駆動型ターゲティング',
    'home.features.data.desc': '人流分析とチケットデータと統合し、広告主がターゲットオーディエンスを正確に特定し、コンバージョンを向上させるのを支援します。',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.subtitle': '今すぐAZIO1ADに参加して、新しい広告取引モデルを体験してください。',
    'home.cta.advertiser': '私は広告主です',
    'home.cta.mediaOwner': '私はメディアオーナーです',

    // Advertiser
    'advertiser.hero.title': '精密なターゲティング、\n真のオーディエンスにリーチ',
    'advertiser.hero.subtitle': '効果のない露出にさようなら。AZIO1ADは台湾全土のプレミアムな場所と直接つながり、データ駆動型の予算で広告効果を最大化します。',
    'advertiser.features.title': '露出だけでなく、深いインタラクションも',
    'advertiser.features.subtitle': '単なる広告枠ではなく、消費者との深いつながりの機会を提供します。',
    'advertiser.features.precise.title': '精密な場所ターゲティング',
    'advertiser.features.precise.desc': '場所のタイプ（展示会、オフィス、小売）と人流特性に基づいて、ターゲット顧客を正確に特定します。',
    'advertiser.features.transparent.title': '透明な価格設定',
    'advertiser.features.transparent.desc': '広告枠の価格とスケジュールを直接確認でき、面倒な問い合わせプロセスを省き、予算管理を改善します。',
    'advertiser.features.interactive.title': 'インタラクティブマーケティングモジュール',
    'advertiser.features.interactive.desc': '抽選やアンケートなどのインタラクティブモジュールをサポートし、受動的な視聴をブランドとの能動的な対話に変えます。',
    'advertiser.steps.title': '簡単な3ステップで開始',
    'advertiser.steps.1.title': '在庫を検索',
    'advertiser.steps.1.desc': '地域や場所のタイプで適切な広告枠をフィルタリングします。',
    'advertiser.steps.2.title': 'オンライン予約',
    'advertiser.steps.2.desc': 'スケジュールと価格を確認し、オンラインで直接予約・支払いを行います。',
    'advertiser.steps.3.title': 'クリエイティブをアップロード',
    'advertiser.steps.3.desc': '広告クリエイティブをアップロードします。システムが自動的に審査し、即座に公開します。',

    // Media Owner
    'media.hero.title': '遊休スクリーンを、\n収益資産に変える',
    'media.hero.subtitle': '面倒な営業開拓は不要です。AZIO1ADは、場所のスクリーンを販売用に掲載し、広告主と自動的にマッチングさせ、簡単に追加収益を生み出すのを支援します。',
    'media.features.title': '場所の価値を最大化',
    'media.features.subtitle': 'スクリーンと広告注文を簡単に管理するための完全な管理ツールを提供します。',
    'media.features.management.title': 'クラウドスクリーン管理',
    'media.features.management.desc': 'クラウドダッシュボードを通じて、いつでもどこでも複数の場所のスクリーンコンテンツと再生スケジュールを管理できます。',
    'media.features.sales.title': '自動販売',
    'media.features.sales.desc': '広告枠の価格と販売可能な時間帯を設定します。システムは手動介入なしに広告主の注文を自動的にマッチングします。',
    'media.features.report.title': '収益レポート',
    'media.features.report.desc': '広告収益と再生データをリアルタイムで確認し、場所の運営状況を把握し、価格戦略を最適化します。',
    'media.steps.title': '簡単設定、即時収益化',
    'media.steps.1.title': '場所を登録',
    'media.steps.1.desc': '場所情報とスクリーン仕様を入力して、アカウント登録を完了します。',
    'media.steps.2.title': 'プレイヤーをインストール',
    'media.steps.2.desc': 'スクリーン機器にAZIO1ADプレイヤーをインストールします。',
    'media.steps.3.title': '収益化を開始',
    'media.steps.3.desc': '販売可能な時間帯と価格を設定し、広告主の注文を待って収益を得ます。',

    // Pricing
    'pricing.title': 'シンプルで透明な料金プラン',
    'pricing.subtitle': '始めたばかりの小さな場所でも、複数の拠点を持つ大企業でも、あなたに合ったプランがあります。',
    'pricing.advertiser.title': '広告主',
    'pricing.advertiser.desc': '登録無料、広告費のみ支払い',
    'pricing.advertiser.price': '0',
    'pricing.advertiser.unit': '/ 月',
    'pricing.advertiser.feature1': 'プレミアム在庫を閲覧',
    'pricing.advertiser.feature2': '透明な価格設定',
    'pricing.advertiser.feature3': '即時公開と追跡',
    'pricing.advertiser.feature4': '基本データレポート',
    'pricing.media.starter.title': 'メディアオーナー - スターター',
    'pricing.media.starter.desc': '単一の場所または少数のスクリーン向け',
    'pricing.media.starter.price': '0',
    'pricing.media.starter.unit': '/ 月',
    'pricing.media.starter.feature1': '1つの場所を管理',
    'pricing.media.starter.feature2': '最大3つのスクリーン',
    'pricing.media.starter.feature3': '基本スケジュール管理',
    'pricing.media.starter.feature4': '5% プラットフォーム手数料',
    'pricing.media.pro.title': 'メディアオーナー - プロ',
    'pricing.media.pro.desc': '複数の場所またはチェーン向け',
    'pricing.media.pro.price': '1,500',
    'pricing.media.pro.unit': '/ 月 / スクリーン',
    'pricing.media.pro.feature1': '無制限の場所管理',
    'pricing.media.pro.feature2': '無制限のスクリーン数',
    'pricing.media.pro.feature3': '高度なスケジュールとインタラクション',
    'pricing.media.pro.feature4': '3% プラットフォーム手数料',
    'pricing.enterprise.title': 'エンタープライズ',
    'pricing.enterprise.desc': '大規模な場所または特別なニーズ向け',
    'pricing.enterprise.price': 'カスタム',
    'pricing.enterprise.unit': '',
    'pricing.enterprise.feature1': '専用API連携',
    'pricing.enterprise.feature2': 'カスタム機能開発',
    'pricing.enterprise.feature3': '専用サポート',
    'pricing.enterprise.feature4': '割引プラットフォーム手数料',
    'pricing.cta': '今すぐ始める',
    'pricing.contact': 'お問い合わせ',

    // About
    'about.hero.title': '私たちについて',
    'about.hero.subtitle': 'AZIO1ADは、技術革新を通じて、公平で透明かつ効率的な場所広告エコシステムを構築することに専念しています。',
    'about.mission.title': '私たちのミッション',
    'about.mission.desc': 'すべてのスクリーンを価値あるものにし、すべての広告がターゲットに正確に届くようにすること。私たちは、デジタルトランスフォーメーションとデータ活用が従来の広告市場の情報の非対称性を打破し、メディアオーナー、広告主、消費者の三方よしの状況を作り出せると信じています。',
    'about.vision.title': '私たちのビジョン',
    'about.vision.desc': '物理空間とデジタル広告をつなぎ、将来のDOOHの標準を定義する、アジアをリードする場所広告取引プラットフォームになること。',
    'about.team.title': '私たちのチーム',
    'about.team.desc': '私たちは、アドテク、ソフトウェア開発、ビジネスコンサルティングの専門家グループであり、豊富な業界経験と革新への情熱を持っています。',

    // Features
    'features.hero.title': '強力な機能、\nすべてのニーズを満たす',
    'features.hero.subtitle': '広告の公開からスクリーン管理まで、AZIO1ADは包括的なソリューションを提供します。',
    'features.list.title': 'コア機能一覧',
    'features.ad.management': '広告スケジュール管理',
    'features.ad.management.desc': '直感的なカレンダーインターフェースで、各スクリーンの広告スケジュールとコンテンツを簡単に管理できます。',
    'features.device.monitoring': 'デバイス状態監視',
    'features.device.monitoring.desc': 'スクリーンの接続状態と再生をリアルタイムで監視し、異常があれば自動的に通知します。',
    'features.data.analytics': 'データ分析レポート',
    'features.data.analytics.desc': '詳細な再生記録、人流データ、収益分析を提供し、意思決定の最適化を支援します。',
    'features.interactive': 'インタラクティブマーケティング',
    'features.interactive.desc': '抽選、投票、アンケートなどのインタラクティブ機能を内蔵し、広告への関与を高めます。',

    // Case Studies
    'case.hero.title': '成功事例',
    'case.hero.subtitle': '他の企業がAZIO1ADでどのように価値を創造しているかをご覧ください。',
    'case.nangang.title': '南港展覧館',
    'case.nangang.desc': 'AZIO1ADデジタルサイネージ管理システムを導入することで、館内の遊休スクリーンを高価値な広告枠に変え、非展示期間の収益を30%増加させることに成功しました。',
    'case.retail.title': 'チェーン小売店',
    'case.retail.desc': 'AZIO1ADネットワーク機能を利用して、台湾全土の50店舗のプロモーションコンテンツを一元管理し、残りの枠を外部ブランドに開放して追加収益を生み出しました。',

    // Get Started
    'getstarted.title': '役割を選択',
    'getstarted.subtitle': '広告を購入したい場合でも、在庫を販売したい場合でも、対応可能です。',
    'getstarted.advertiser.title': '私は広告主です',
    'getstarted.advertiser.subtitle': 'Advertiser',
    'getstarted.advertiser.desc': 'ブランドや商品を宣伝するために広告枠を購入したい。',
    'getstarted.advertiser.feature1': 'プレミアム在庫を閲覧',
    'getstarted.advertiser.feature2': '透明な価格設定、オンライン注文',
    'getstarted.advertiser.feature3': '即時公開、成果追跡',
    'getstarted.advertiser.cta': '私は広告主です',
    'getstarted.media.title': '私はメディアオーナーです',
    'getstarted.media.subtitle': 'Media Owner',
    'getstarted.media.desc': 'トラフィックを収益化するために広告スクリーンを掲載したい。',
    'getstarted.media.feature1': '複数場所のスクリーンを簡単管理',
    'getstarted.media.feature2': 'カスタム枠と販売価格',
    'getstarted.media.feature3': '自動スケジュールと収益レポート',
    'getstarted.media.cta': '私はメディアオーナーです',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
